# CMake generated Testfile for 
# Source directory: F:/code/3rdparty/PROJ/PROJ-master/test/unit
# Build directory: F:/code/3rdparty/PROJ/vs2019/test/unit
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(proj_pj_transform_test "F:/code/3rdparty/PROJ/vs2019/bin/Debug/proj_pj_transform_test.exe")
  set_tests_properties(proj_pj_transform_test PROPERTIES  ENVIRONMENT "PROJ_SKIP_READ_USER_WRITABLE_DIRECTORY=YES;PROJ_LIB=F:/code/3rdparty/PROJ/vs2019/data/for_tests;PROJ_SOURCE_DATA=F:/code/3rdparty/PROJ/PROJ-master/data" _BACKTRACE_TRIPLES "F:/code/3rdparty/PROJ/PROJ-master/test/unit/CMakeLists.txt;78;add_test;F:/code/3rdparty/PROJ/PROJ-master/test/unit/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(proj_pj_transform_test "F:/code/3rdparty/PROJ/vs2019/bin/Release/proj_pj_transform_test.exe")
  set_tests_properties(proj_pj_transform_test PROPERTIES  ENVIRONMENT "PROJ_SKIP_READ_USER_WRITABLE_DIRECTORY=YES;PROJ_LIB=F:/code/3rdparty/PROJ/vs2019/data/for_tests;PROJ_SOURCE_DATA=F:/code/3rdparty/PROJ/PROJ-master/data" _BACKTRACE_TRIPLES "F:/code/3rdparty/PROJ/PROJ-master/test/unit/CMakeLists.txt;78;add_test;F:/code/3rdparty/PROJ/PROJ-master/test/unit/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(proj_pj_transform_test "F:/code/3rdparty/PROJ/vs2019/bin/MinSizeRel/proj_pj_transform_test.exe")
  set_tests_properties(proj_pj_transform_test PROPERTIES  ENVIRONMENT "PROJ_SKIP_READ_USER_WRITABLE_DIRECTORY=YES;PROJ_LIB=F:/code/3rdparty/PROJ/vs2019/data/for_tests;PROJ_SOURCE_DATA=F:/code/3rdparty/PROJ/PROJ-master/data" _BACKTRACE_TRIPLES "F:/code/3rdparty/PROJ/PROJ-master/test/unit/CMakeLists.txt;78;add_test;F:/code/3rdparty/PROJ/PROJ-master/test/unit/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(proj_pj_transform_test "F:/code/3rdparty/PROJ/vs2019/bin/RelWithDebInfo/proj_pj_transform_test.exe")
  set_tests_properties(proj_pj_transform_test PROPERTIES  ENVIRONMENT "PROJ_SKIP_READ_USER_WRITABLE_DIRECTORY=YES;PROJ_LIB=F:/code/3rdparty/PROJ/vs2019/data/for_tests;PROJ_SOURCE_DATA=F:/code/3rdparty/PROJ/PROJ-master/data" _BACKTRACE_TRIPLES "F:/code/3rdparty/PROJ/PROJ-master/test/unit/CMakeLists.txt;78;add_test;F:/code/3rdparty/PROJ/PROJ-master/test/unit/CMakeLists.txt;0;")
else()
  add_test(proj_pj_transform_test NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(proj_errno_string_test "F:/code/3rdparty/PROJ/vs2019/bin/Debug/proj_errno_string_test.exe")
  set_tests_properties(proj_errno_string_test PROPERTIES  ENVIRONMENT "PROJ_SKIP_READ_USER_WRITABLE_DIRECTORY=YES;PROJ_LIB=F:/code/3rdparty/PROJ/vs2019/data/for_tests;PROJ_SOURCE_DATA=F:/code/3rdparty/PROJ/PROJ-master/data" _BACKTRACE_TRIPLES "F:/code/3rdparty/PROJ/PROJ-master/test/unit/CMakeLists.txt;89;add_test;F:/code/3rdparty/PROJ/PROJ-master/test/unit/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(proj_errno_string_test "F:/code/3rdparty/PROJ/vs2019/bin/Release/proj_errno_string_test.exe")
  set_tests_properties(proj_errno_string_test PROPERTIES  ENVIRONMENT "PROJ_SKIP_READ_USER_WRITABLE_DIRECTORY=YES;PROJ_LIB=F:/code/3rdparty/PROJ/vs2019/data/for_tests;PROJ_SOURCE_DATA=F:/code/3rdparty/PROJ/PROJ-master/data" _BACKTRACE_TRIPLES "F:/code/3rdparty/PROJ/PROJ-master/test/unit/CMakeLists.txt;89;add_test;F:/code/3rdparty/PROJ/PROJ-master/test/unit/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(proj_errno_string_test "F:/code/3rdparty/PROJ/vs2019/bin/MinSizeRel/proj_errno_string_test.exe")
  set_tests_properties(proj_errno_string_test PROPERTIES  ENVIRONMENT "PROJ_SKIP_READ_USER_WRITABLE_DIRECTORY=YES;PROJ_LIB=F:/code/3rdparty/PROJ/vs2019/data/for_tests;PROJ_SOURCE_DATA=F:/code/3rdparty/PROJ/PROJ-master/data" _BACKTRACE_TRIPLES "F:/code/3rdparty/PROJ/PROJ-master/test/unit/CMakeLists.txt;89;add_test;F:/code/3rdparty/PROJ/PROJ-master/test/unit/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(proj_errno_string_test "F:/code/3rdparty/PROJ/vs2019/bin/RelWithDebInfo/proj_errno_string_test.exe")
  set_tests_properties(proj_errno_string_test PROPERTIES  ENVIRONMENT "PROJ_SKIP_READ_USER_WRITABLE_DIRECTORY=YES;PROJ_LIB=F:/code/3rdparty/PROJ/vs2019/data/for_tests;PROJ_SOURCE_DATA=F:/code/3rdparty/PROJ/PROJ-master/data" _BACKTRACE_TRIPLES "F:/code/3rdparty/PROJ/PROJ-master/test/unit/CMakeLists.txt;89;add_test;F:/code/3rdparty/PROJ/PROJ-master/test/unit/CMakeLists.txt;0;")
else()
  add_test(proj_errno_string_test NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(proj_angular_io_test "F:/code/3rdparty/PROJ/vs2019/bin/Debug/proj_angular_io_test.exe")
  set_tests_properties(proj_angular_io_test PROPERTIES  ENVIRONMENT "PROJ_SKIP_READ_USER_WRITABLE_DIRECTORY=YES;PROJ_LIB=F:/code/3rdparty/PROJ/vs2019/data/for_tests;PROJ_SOURCE_DATA=F:/code/3rdparty/PROJ/PROJ-master/data" _BACKTRACE_TRIPLES "F:/code/3rdparty/PROJ/PROJ-master/test/unit/CMakeLists.txt;99;add_test;F:/code/3rdparty/PROJ/PROJ-master/test/unit/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(proj_angular_io_test "F:/code/3rdparty/PROJ/vs2019/bin/Release/proj_angular_io_test.exe")
  set_tests_properties(proj_angular_io_test PROPERTIES  ENVIRONMENT "PROJ_SKIP_READ_USER_WRITABLE_DIRECTORY=YES;PROJ_LIB=F:/code/3rdparty/PROJ/vs2019/data/for_tests;PROJ_SOURCE_DATA=F:/code/3rdparty/PROJ/PROJ-master/data" _BACKTRACE_TRIPLES "F:/code/3rdparty/PROJ/PROJ-master/test/unit/CMakeLists.txt;99;add_test;F:/code/3rdparty/PROJ/PROJ-master/test/unit/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(proj_angular_io_test "F:/code/3rdparty/PROJ/vs2019/bin/MinSizeRel/proj_angular_io_test.exe")
  set_tests_properties(proj_angular_io_test PROPERTIES  ENVIRONMENT "PROJ_SKIP_READ_USER_WRITABLE_DIRECTORY=YES;PROJ_LIB=F:/code/3rdparty/PROJ/vs2019/data/for_tests;PROJ_SOURCE_DATA=F:/code/3rdparty/PROJ/PROJ-master/data" _BACKTRACE_TRIPLES "F:/code/3rdparty/PROJ/PROJ-master/test/unit/CMakeLists.txt;99;add_test;F:/code/3rdparty/PROJ/PROJ-master/test/unit/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(proj_angular_io_test "F:/code/3rdparty/PROJ/vs2019/bin/RelWithDebInfo/proj_angular_io_test.exe")
  set_tests_properties(proj_angular_io_test PROPERTIES  ENVIRONMENT "PROJ_SKIP_READ_USER_WRITABLE_DIRECTORY=YES;PROJ_LIB=F:/code/3rdparty/PROJ/vs2019/data/for_tests;PROJ_SOURCE_DATA=F:/code/3rdparty/PROJ/PROJ-master/data" _BACKTRACE_TRIPLES "F:/code/3rdparty/PROJ/PROJ-master/test/unit/CMakeLists.txt;99;add_test;F:/code/3rdparty/PROJ/PROJ-master/test/unit/CMakeLists.txt;0;")
else()
  add_test(proj_angular_io_test NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(proj_context_test "F:/code/3rdparty/PROJ/vs2019/bin/Debug/proj_context_test.exe")
  set_tests_properties(proj_context_test PROPERTIES  ENVIRONMENT "PROJ_SKIP_READ_USER_WRITABLE_DIRECTORY=YES;PROJ_LIB=F:/code/3rdparty/PROJ/vs2019/data/for_tests;PROJ_SOURCE_DATA=F:/code/3rdparty/PROJ/PROJ-master/data" _BACKTRACE_TRIPLES "F:/code/3rdparty/PROJ/PROJ-master/test/unit/CMakeLists.txt;109;add_test;F:/code/3rdparty/PROJ/PROJ-master/test/unit/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(proj_context_test "F:/code/3rdparty/PROJ/vs2019/bin/Release/proj_context_test.exe")
  set_tests_properties(proj_context_test PROPERTIES  ENVIRONMENT "PROJ_SKIP_READ_USER_WRITABLE_DIRECTORY=YES;PROJ_LIB=F:/code/3rdparty/PROJ/vs2019/data/for_tests;PROJ_SOURCE_DATA=F:/code/3rdparty/PROJ/PROJ-master/data" _BACKTRACE_TRIPLES "F:/code/3rdparty/PROJ/PROJ-master/test/unit/CMakeLists.txt;109;add_test;F:/code/3rdparty/PROJ/PROJ-master/test/unit/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(proj_context_test "F:/code/3rdparty/PROJ/vs2019/bin/MinSizeRel/proj_context_test.exe")
  set_tests_properties(proj_context_test PROPERTIES  ENVIRONMENT "PROJ_SKIP_READ_USER_WRITABLE_DIRECTORY=YES;PROJ_LIB=F:/code/3rdparty/PROJ/vs2019/data/for_tests;PROJ_SOURCE_DATA=F:/code/3rdparty/PROJ/PROJ-master/data" _BACKTRACE_TRIPLES "F:/code/3rdparty/PROJ/PROJ-master/test/unit/CMakeLists.txt;109;add_test;F:/code/3rdparty/PROJ/PROJ-master/test/unit/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(proj_context_test "F:/code/3rdparty/PROJ/vs2019/bin/RelWithDebInfo/proj_context_test.exe")
  set_tests_properties(proj_context_test PROPERTIES  ENVIRONMENT "PROJ_SKIP_READ_USER_WRITABLE_DIRECTORY=YES;PROJ_LIB=F:/code/3rdparty/PROJ/vs2019/data/for_tests;PROJ_SOURCE_DATA=F:/code/3rdparty/PROJ/PROJ-master/data" _BACKTRACE_TRIPLES "F:/code/3rdparty/PROJ/PROJ-master/test/unit/CMakeLists.txt;109;add_test;F:/code/3rdparty/PROJ/PROJ-master/test/unit/CMakeLists.txt;0;")
else()
  add_test(proj_context_test NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(pj_phi2_test "F:/code/3rdparty/PROJ/vs2019/bin/Debug/pj_phi2_test.exe")
  set_tests_properties(pj_phi2_test PROPERTIES  ENVIRONMENT "PROJ_SKIP_READ_USER_WRITABLE_DIRECTORY=YES;PROJ_LIB=F:/code/3rdparty/PROJ/vs2019/data/for_tests;PROJ_SOURCE_DATA=F:/code/3rdparty/PROJ/PROJ-master/data" _BACKTRACE_TRIPLES "F:/code/3rdparty/PROJ/PROJ-master/test/unit/CMakeLists.txt;122;add_test;F:/code/3rdparty/PROJ/PROJ-master/test/unit/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(pj_phi2_test "F:/code/3rdparty/PROJ/vs2019/bin/Release/pj_phi2_test.exe")
  set_tests_properties(pj_phi2_test PROPERTIES  ENVIRONMENT "PROJ_SKIP_READ_USER_WRITABLE_DIRECTORY=YES;PROJ_LIB=F:/code/3rdparty/PROJ/vs2019/data/for_tests;PROJ_SOURCE_DATA=F:/code/3rdparty/PROJ/PROJ-master/data" _BACKTRACE_TRIPLES "F:/code/3rdparty/PROJ/PROJ-master/test/unit/CMakeLists.txt;122;add_test;F:/code/3rdparty/PROJ/PROJ-master/test/unit/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(pj_phi2_test "F:/code/3rdparty/PROJ/vs2019/bin/MinSizeRel/pj_phi2_test.exe")
  set_tests_properties(pj_phi2_test PROPERTIES  ENVIRONMENT "PROJ_SKIP_READ_USER_WRITABLE_DIRECTORY=YES;PROJ_LIB=F:/code/3rdparty/PROJ/vs2019/data/for_tests;PROJ_SOURCE_DATA=F:/code/3rdparty/PROJ/PROJ-master/data" _BACKTRACE_TRIPLES "F:/code/3rdparty/PROJ/PROJ-master/test/unit/CMakeLists.txt;122;add_test;F:/code/3rdparty/PROJ/PROJ-master/test/unit/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(pj_phi2_test "F:/code/3rdparty/PROJ/vs2019/bin/RelWithDebInfo/pj_phi2_test.exe")
  set_tests_properties(pj_phi2_test PROPERTIES  ENVIRONMENT "PROJ_SKIP_READ_USER_WRITABLE_DIRECTORY=YES;PROJ_LIB=F:/code/3rdparty/PROJ/vs2019/data/for_tests;PROJ_SOURCE_DATA=F:/code/3rdparty/PROJ/PROJ-master/data" _BACKTRACE_TRIPLES "F:/code/3rdparty/PROJ/PROJ-master/test/unit/CMakeLists.txt;122;add_test;F:/code/3rdparty/PROJ/PROJ-master/test/unit/CMakeLists.txt;0;")
else()
  add_test(pj_phi2_test NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(proj_test_cpp_api "F:/code/3rdparty/PROJ/vs2019/bin/Debug/proj_test_cpp_api.exe")
  set_tests_properties(proj_test_cpp_api PROPERTIES  ENVIRONMENT "PROJ_SKIP_READ_USER_WRITABLE_DIRECTORY=YES;PROJ_LIB=F:/code/3rdparty/PROJ/vs2019/data/for_tests;PROJ_SOURCE_DATA=F:/code/3rdparty/PROJ/PROJ-master/data" _BACKTRACE_TRIPLES "F:/code/3rdparty/PROJ/PROJ-master/test/unit/CMakeLists.txt;143;add_test;F:/code/3rdparty/PROJ/PROJ-master/test/unit/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(proj_test_cpp_api "F:/code/3rdparty/PROJ/vs2019/bin/Release/proj_test_cpp_api.exe")
  set_tests_properties(proj_test_cpp_api PROPERTIES  ENVIRONMENT "PROJ_SKIP_READ_USER_WRITABLE_DIRECTORY=YES;PROJ_LIB=F:/code/3rdparty/PROJ/vs2019/data/for_tests;PROJ_SOURCE_DATA=F:/code/3rdparty/PROJ/PROJ-master/data" _BACKTRACE_TRIPLES "F:/code/3rdparty/PROJ/PROJ-master/test/unit/CMakeLists.txt;143;add_test;F:/code/3rdparty/PROJ/PROJ-master/test/unit/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(proj_test_cpp_api "F:/code/3rdparty/PROJ/vs2019/bin/MinSizeRel/proj_test_cpp_api.exe")
  set_tests_properties(proj_test_cpp_api PROPERTIES  ENVIRONMENT "PROJ_SKIP_READ_USER_WRITABLE_DIRECTORY=YES;PROJ_LIB=F:/code/3rdparty/PROJ/vs2019/data/for_tests;PROJ_SOURCE_DATA=F:/code/3rdparty/PROJ/PROJ-master/data" _BACKTRACE_TRIPLES "F:/code/3rdparty/PROJ/PROJ-master/test/unit/CMakeLists.txt;143;add_test;F:/code/3rdparty/PROJ/PROJ-master/test/unit/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(proj_test_cpp_api "F:/code/3rdparty/PROJ/vs2019/bin/RelWithDebInfo/proj_test_cpp_api.exe")
  set_tests_properties(proj_test_cpp_api PROPERTIES  ENVIRONMENT "PROJ_SKIP_READ_USER_WRITABLE_DIRECTORY=YES;PROJ_LIB=F:/code/3rdparty/PROJ/vs2019/data/for_tests;PROJ_SOURCE_DATA=F:/code/3rdparty/PROJ/PROJ-master/data" _BACKTRACE_TRIPLES "F:/code/3rdparty/PROJ/PROJ-master/test/unit/CMakeLists.txt;143;add_test;F:/code/3rdparty/PROJ/PROJ-master/test/unit/CMakeLists.txt;0;")
else()
  add_test(proj_test_cpp_api NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(gie_self_tests "F:/code/3rdparty/PROJ/vs2019/bin/Debug/gie_self_tests.exe")
  set_tests_properties(gie_self_tests PROPERTIES  ENVIRONMENT "PROJ_SKIP_READ_USER_WRITABLE_DIRECTORY=YES;PROJ_LIB=F:/code/3rdparty/PROJ/vs2019/data/for_tests;PROJ_SOURCE_DATA=F:/code/3rdparty/PROJ/PROJ-master/data" _BACKTRACE_TRIPLES "F:/code/3rdparty/PROJ/PROJ-master/test/unit/CMakeLists.txt;154;add_test;F:/code/3rdparty/PROJ/PROJ-master/test/unit/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(gie_self_tests "F:/code/3rdparty/PROJ/vs2019/bin/Release/gie_self_tests.exe")
  set_tests_properties(gie_self_tests PROPERTIES  ENVIRONMENT "PROJ_SKIP_READ_USER_WRITABLE_DIRECTORY=YES;PROJ_LIB=F:/code/3rdparty/PROJ/vs2019/data/for_tests;PROJ_SOURCE_DATA=F:/code/3rdparty/PROJ/PROJ-master/data" _BACKTRACE_TRIPLES "F:/code/3rdparty/PROJ/PROJ-master/test/unit/CMakeLists.txt;154;add_test;F:/code/3rdparty/PROJ/PROJ-master/test/unit/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(gie_self_tests "F:/code/3rdparty/PROJ/vs2019/bin/MinSizeRel/gie_self_tests.exe")
  set_tests_properties(gie_self_tests PROPERTIES  ENVIRONMENT "PROJ_SKIP_READ_USER_WRITABLE_DIRECTORY=YES;PROJ_LIB=F:/code/3rdparty/PROJ/vs2019/data/for_tests;PROJ_SOURCE_DATA=F:/code/3rdparty/PROJ/PROJ-master/data" _BACKTRACE_TRIPLES "F:/code/3rdparty/PROJ/PROJ-master/test/unit/CMakeLists.txt;154;add_test;F:/code/3rdparty/PROJ/PROJ-master/test/unit/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(gie_self_tests "F:/code/3rdparty/PROJ/vs2019/bin/RelWithDebInfo/gie_self_tests.exe")
  set_tests_properties(gie_self_tests PROPERTIES  ENVIRONMENT "PROJ_SKIP_READ_USER_WRITABLE_DIRECTORY=YES;PROJ_LIB=F:/code/3rdparty/PROJ/vs2019/data/for_tests;PROJ_SOURCE_DATA=F:/code/3rdparty/PROJ/PROJ-master/data" _BACKTRACE_TRIPLES "F:/code/3rdparty/PROJ/PROJ-master/test/unit/CMakeLists.txt;154;add_test;F:/code/3rdparty/PROJ/PROJ-master/test/unit/CMakeLists.txt;0;")
else()
  add_test(gie_self_tests NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(test_network "F:/code/3rdparty/PROJ/vs2019/bin/Debug/test_network.exe")
  set_tests_properties(test_network PROPERTIES  ENVIRONMENT "PROJ_SKIP_READ_USER_WRITABLE_DIRECTORY=YES;PROJ_LIB=F:/code/3rdparty/PROJ/vs2019/data/for_tests;PROJ_SOURCE_DATA=F:/code/3rdparty/PROJ/PROJ-master/data" _BACKTRACE_TRIPLES "F:/code/3rdparty/PROJ/PROJ-master/test/unit/CMakeLists.txt;170;add_test;F:/code/3rdparty/PROJ/PROJ-master/test/unit/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(test_network "F:/code/3rdparty/PROJ/vs2019/bin/Release/test_network.exe")
  set_tests_properties(test_network PROPERTIES  ENVIRONMENT "PROJ_SKIP_READ_USER_WRITABLE_DIRECTORY=YES;PROJ_LIB=F:/code/3rdparty/PROJ/vs2019/data/for_tests;PROJ_SOURCE_DATA=F:/code/3rdparty/PROJ/PROJ-master/data" _BACKTRACE_TRIPLES "F:/code/3rdparty/PROJ/PROJ-master/test/unit/CMakeLists.txt;170;add_test;F:/code/3rdparty/PROJ/PROJ-master/test/unit/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(test_network "F:/code/3rdparty/PROJ/vs2019/bin/MinSizeRel/test_network.exe")
  set_tests_properties(test_network PROPERTIES  ENVIRONMENT "PROJ_SKIP_READ_USER_WRITABLE_DIRECTORY=YES;PROJ_LIB=F:/code/3rdparty/PROJ/vs2019/data/for_tests;PROJ_SOURCE_DATA=F:/code/3rdparty/PROJ/PROJ-master/data" _BACKTRACE_TRIPLES "F:/code/3rdparty/PROJ/PROJ-master/test/unit/CMakeLists.txt;170;add_test;F:/code/3rdparty/PROJ/PROJ-master/test/unit/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(test_network "F:/code/3rdparty/PROJ/vs2019/bin/RelWithDebInfo/test_network.exe")
  set_tests_properties(test_network PROPERTIES  ENVIRONMENT "PROJ_SKIP_READ_USER_WRITABLE_DIRECTORY=YES;PROJ_LIB=F:/code/3rdparty/PROJ/vs2019/data/for_tests;PROJ_SOURCE_DATA=F:/code/3rdparty/PROJ/PROJ-master/data" _BACKTRACE_TRIPLES "F:/code/3rdparty/PROJ/PROJ-master/test/unit/CMakeLists.txt;170;add_test;F:/code/3rdparty/PROJ/PROJ-master/test/unit/CMakeLists.txt;0;")
else()
  add_test(test_network NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(test_defmodel "F:/code/3rdparty/PROJ/vs2019/bin/Debug/test_defmodel.exe")
  set_tests_properties(test_defmodel PROPERTIES  ENVIRONMENT "PROJ_SKIP_READ_USER_WRITABLE_DIRECTORY=YES;PROJ_LIB=F:/code/3rdparty/PROJ/vs2019/data/for_tests;PROJ_SOURCE_DATA=F:/code/3rdparty/PROJ/PROJ-master/data" _BACKTRACE_TRIPLES "F:/code/3rdparty/PROJ/PROJ-master/test/unit/CMakeLists.txt;181;add_test;F:/code/3rdparty/PROJ/PROJ-master/test/unit/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(test_defmodel "F:/code/3rdparty/PROJ/vs2019/bin/Release/test_defmodel.exe")
  set_tests_properties(test_defmodel PROPERTIES  ENVIRONMENT "PROJ_SKIP_READ_USER_WRITABLE_DIRECTORY=YES;PROJ_LIB=F:/code/3rdparty/PROJ/vs2019/data/for_tests;PROJ_SOURCE_DATA=F:/code/3rdparty/PROJ/PROJ-master/data" _BACKTRACE_TRIPLES "F:/code/3rdparty/PROJ/PROJ-master/test/unit/CMakeLists.txt;181;add_test;F:/code/3rdparty/PROJ/PROJ-master/test/unit/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(test_defmodel "F:/code/3rdparty/PROJ/vs2019/bin/MinSizeRel/test_defmodel.exe")
  set_tests_properties(test_defmodel PROPERTIES  ENVIRONMENT "PROJ_SKIP_READ_USER_WRITABLE_DIRECTORY=YES;PROJ_LIB=F:/code/3rdparty/PROJ/vs2019/data/for_tests;PROJ_SOURCE_DATA=F:/code/3rdparty/PROJ/PROJ-master/data" _BACKTRACE_TRIPLES "F:/code/3rdparty/PROJ/PROJ-master/test/unit/CMakeLists.txt;181;add_test;F:/code/3rdparty/PROJ/PROJ-master/test/unit/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(test_defmodel "F:/code/3rdparty/PROJ/vs2019/bin/RelWithDebInfo/test_defmodel.exe")
  set_tests_properties(test_defmodel PROPERTIES  ENVIRONMENT "PROJ_SKIP_READ_USER_WRITABLE_DIRECTORY=YES;PROJ_LIB=F:/code/3rdparty/PROJ/vs2019/data/for_tests;PROJ_SOURCE_DATA=F:/code/3rdparty/PROJ/PROJ-master/data" _BACKTRACE_TRIPLES "F:/code/3rdparty/PROJ/PROJ-master/test/unit/CMakeLists.txt;181;add_test;F:/code/3rdparty/PROJ/PROJ-master/test/unit/CMakeLists.txt;0;")
else()
  add_test(test_defmodel NOT_AVAILABLE)
endif()
subdirs("../../googletest-build")
