# CMake generated Testfile for 
# Source directory: F:/code/3rdparty/PROJ/PROJ-master/test
# Build directory: F:/code/3rdparty/PROJ/vs2019/test
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(Builtins "F:/code/3rdparty/PROJ/vs2019/bin/gie_d.exe" "F:/code/3rdparty/PROJ/PROJ-master/test/gie/builtins.gie")
  set_tests_properties(Builtins PROPERTIES  ENVIRONMENT "PROJ_SKIP_READ_USER_WRITABLE_DIRECTORY=YES;PROJ_LIB=F:/code/3rdparty/PROJ/vs2019/data/for_tests" WORKING_DIRECTORY "F:/code/3rdparty/PROJ/PROJ-master/test" _BACKTRACE_TRIPLES "F:/code/3rdparty/PROJ/PROJ-master/cmake/ProjTest.cmake;31;add_test;F:/code/3rdparty/PROJ/PROJ-master/test/CMakeLists.txt;4;proj_add_gie_test;F:/code/3rdparty/PROJ/PROJ-master/test/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(Builtins "F:/code/3rdparty/PROJ/vs2019/bin/gie.exe" "F:/code/3rdparty/PROJ/PROJ-master/test/gie/builtins.gie")
  set_tests_properties(Builtins PROPERTIES  ENVIRONMENT "PROJ_SKIP_READ_USER_WRITABLE_DIRECTORY=YES;PROJ_LIB=F:/code/3rdparty/PROJ/vs2019/data/for_tests" WORKING_DIRECTORY "F:/code/3rdparty/PROJ/PROJ-master/test" _BACKTRACE_TRIPLES "F:/code/3rdparty/PROJ/PROJ-master/cmake/ProjTest.cmake;31;add_test;F:/code/3rdparty/PROJ/PROJ-master/test/CMakeLists.txt;4;proj_add_gie_test;F:/code/3rdparty/PROJ/PROJ-master/test/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(Builtins "F:/code/3rdparty/PROJ/vs2019/bin/gie.exe" "F:/code/3rdparty/PROJ/PROJ-master/test/gie/builtins.gie")
  set_tests_properties(Builtins PROPERTIES  ENVIRONMENT "PROJ_SKIP_READ_USER_WRITABLE_DIRECTORY=YES;PROJ_LIB=F:/code/3rdparty/PROJ/vs2019/data/for_tests" WORKING_DIRECTORY "F:/code/3rdparty/PROJ/PROJ-master/test" _BACKTRACE_TRIPLES "F:/code/3rdparty/PROJ/PROJ-master/cmake/ProjTest.cmake;31;add_test;F:/code/3rdparty/PROJ/PROJ-master/test/CMakeLists.txt;4;proj_add_gie_test;F:/code/3rdparty/PROJ/PROJ-master/test/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(Builtins "F:/code/3rdparty/PROJ/vs2019/bin/gie.exe" "F:/code/3rdparty/PROJ/PROJ-master/test/gie/builtins.gie")
  set_tests_properties(Builtins PROPERTIES  ENVIRONMENT "PROJ_SKIP_READ_USER_WRITABLE_DIRECTORY=YES;PROJ_LIB=F:/code/3rdparty/PROJ/vs2019/data/for_tests" WORKING_DIRECTORY "F:/code/3rdparty/PROJ/PROJ-master/test" _BACKTRACE_TRIPLES "F:/code/3rdparty/PROJ/PROJ-master/cmake/ProjTest.cmake;31;add_test;F:/code/3rdparty/PROJ/PROJ-master/test/CMakeLists.txt;4;proj_add_gie_test;F:/code/3rdparty/PROJ/PROJ-master/test/CMakeLists.txt;0;")
else()
  add_test(Builtins NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(Builtins2 "F:/code/3rdparty/PROJ/vs2019/bin/gie_d.exe" "F:/code/3rdparty/PROJ/PROJ-master/test/gie/more_builtins.gie")
  set_tests_properties(Builtins2 PROPERTIES  ENVIRONMENT "PROJ_SKIP_READ_USER_WRITABLE_DIRECTORY=YES;PROJ_LIB=F:/code/3rdparty/PROJ/vs2019/data/for_tests" WORKING_DIRECTORY "F:/code/3rdparty/PROJ/PROJ-master/test" _BACKTRACE_TRIPLES "F:/code/3rdparty/PROJ/PROJ-master/cmake/ProjTest.cmake;31;add_test;F:/code/3rdparty/PROJ/PROJ-master/test/CMakeLists.txt;5;proj_add_gie_test;F:/code/3rdparty/PROJ/PROJ-master/test/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(Builtins2 "F:/code/3rdparty/PROJ/vs2019/bin/gie.exe" "F:/code/3rdparty/PROJ/PROJ-master/test/gie/more_builtins.gie")
  set_tests_properties(Builtins2 PROPERTIES  ENVIRONMENT "PROJ_SKIP_READ_USER_WRITABLE_DIRECTORY=YES;PROJ_LIB=F:/code/3rdparty/PROJ/vs2019/data/for_tests" WORKING_DIRECTORY "F:/code/3rdparty/PROJ/PROJ-master/test" _BACKTRACE_TRIPLES "F:/code/3rdparty/PROJ/PROJ-master/cmake/ProjTest.cmake;31;add_test;F:/code/3rdparty/PROJ/PROJ-master/test/CMakeLists.txt;5;proj_add_gie_test;F:/code/3rdparty/PROJ/PROJ-master/test/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(Builtins2 "F:/code/3rdparty/PROJ/vs2019/bin/gie.exe" "F:/code/3rdparty/PROJ/PROJ-master/test/gie/more_builtins.gie")
  set_tests_properties(Builtins2 PROPERTIES  ENVIRONMENT "PROJ_SKIP_READ_USER_WRITABLE_DIRECTORY=YES;PROJ_LIB=F:/code/3rdparty/PROJ/vs2019/data/for_tests" WORKING_DIRECTORY "F:/code/3rdparty/PROJ/PROJ-master/test" _BACKTRACE_TRIPLES "F:/code/3rdparty/PROJ/PROJ-master/cmake/ProjTest.cmake;31;add_test;F:/code/3rdparty/PROJ/PROJ-master/test/CMakeLists.txt;5;proj_add_gie_test;F:/code/3rdparty/PROJ/PROJ-master/test/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(Builtins2 "F:/code/3rdparty/PROJ/vs2019/bin/gie.exe" "F:/code/3rdparty/PROJ/PROJ-master/test/gie/more_builtins.gie")
  set_tests_properties(Builtins2 PROPERTIES  ENVIRONMENT "PROJ_SKIP_READ_USER_WRITABLE_DIRECTORY=YES;PROJ_LIB=F:/code/3rdparty/PROJ/vs2019/data/for_tests" WORKING_DIRECTORY "F:/code/3rdparty/PROJ/PROJ-master/test" _BACKTRACE_TRIPLES "F:/code/3rdparty/PROJ/PROJ-master/cmake/ProjTest.cmake;31;add_test;F:/code/3rdparty/PROJ/PROJ-master/test/CMakeLists.txt;5;proj_add_gie_test;F:/code/3rdparty/PROJ/PROJ-master/test/CMakeLists.txt;0;")
else()
  add_test(Builtins2 NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(Axisswap "F:/code/3rdparty/PROJ/vs2019/bin/gie_d.exe" "F:/code/3rdparty/PROJ/PROJ-master/test/gie/axisswap.gie")
  set_tests_properties(Axisswap PROPERTIES  ENVIRONMENT "PROJ_SKIP_READ_USER_WRITABLE_DIRECTORY=YES;PROJ_LIB=F:/code/3rdparty/PROJ/vs2019/data/for_tests" WORKING_DIRECTORY "F:/code/3rdparty/PROJ/PROJ-master/test" _BACKTRACE_TRIPLES "F:/code/3rdparty/PROJ/PROJ-master/cmake/ProjTest.cmake;31;add_test;F:/code/3rdparty/PROJ/PROJ-master/test/CMakeLists.txt;6;proj_add_gie_test;F:/code/3rdparty/PROJ/PROJ-master/test/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(Axisswap "F:/code/3rdparty/PROJ/vs2019/bin/gie.exe" "F:/code/3rdparty/PROJ/PROJ-master/test/gie/axisswap.gie")
  set_tests_properties(Axisswap PROPERTIES  ENVIRONMENT "PROJ_SKIP_READ_USER_WRITABLE_DIRECTORY=YES;PROJ_LIB=F:/code/3rdparty/PROJ/vs2019/data/for_tests" WORKING_DIRECTORY "F:/code/3rdparty/PROJ/PROJ-master/test" _BACKTRACE_TRIPLES "F:/code/3rdparty/PROJ/PROJ-master/cmake/ProjTest.cmake;31;add_test;F:/code/3rdparty/PROJ/PROJ-master/test/CMakeLists.txt;6;proj_add_gie_test;F:/code/3rdparty/PROJ/PROJ-master/test/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(Axisswap "F:/code/3rdparty/PROJ/vs2019/bin/gie.exe" "F:/code/3rdparty/PROJ/PROJ-master/test/gie/axisswap.gie")
  set_tests_properties(Axisswap PROPERTIES  ENVIRONMENT "PROJ_SKIP_READ_USER_WRITABLE_DIRECTORY=YES;PROJ_LIB=F:/code/3rdparty/PROJ/vs2019/data/for_tests" WORKING_DIRECTORY "F:/code/3rdparty/PROJ/PROJ-master/test" _BACKTRACE_TRIPLES "F:/code/3rdparty/PROJ/PROJ-master/cmake/ProjTest.cmake;31;add_test;F:/code/3rdparty/PROJ/PROJ-master/test/CMakeLists.txt;6;proj_add_gie_test;F:/code/3rdparty/PROJ/PROJ-master/test/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(Axisswap "F:/code/3rdparty/PROJ/vs2019/bin/gie.exe" "F:/code/3rdparty/PROJ/PROJ-master/test/gie/axisswap.gie")
  set_tests_properties(Axisswap PROPERTIES  ENVIRONMENT "PROJ_SKIP_READ_USER_WRITABLE_DIRECTORY=YES;PROJ_LIB=F:/code/3rdparty/PROJ/vs2019/data/for_tests" WORKING_DIRECTORY "F:/code/3rdparty/PROJ/PROJ-master/test" _BACKTRACE_TRIPLES "F:/code/3rdparty/PROJ/PROJ-master/cmake/ProjTest.cmake;31;add_test;F:/code/3rdparty/PROJ/PROJ-master/test/CMakeLists.txt;6;proj_add_gie_test;F:/code/3rdparty/PROJ/PROJ-master/test/CMakeLists.txt;0;")
else()
  add_test(Axisswap NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(Deformation "F:/code/3rdparty/PROJ/vs2019/bin/gie_d.exe" "F:/code/3rdparty/PROJ/PROJ-master/test/gie/deformation.gie")
  set_tests_properties(Deformation PROPERTIES  ENVIRONMENT "PROJ_SKIP_READ_USER_WRITABLE_DIRECTORY=YES;PROJ_LIB=F:/code/3rdparty/PROJ/vs2019/data/for_tests" WORKING_DIRECTORY "F:/code/3rdparty/PROJ/PROJ-master/test" _BACKTRACE_TRIPLES "F:/code/3rdparty/PROJ/PROJ-master/cmake/ProjTest.cmake;31;add_test;F:/code/3rdparty/PROJ/PROJ-master/test/CMakeLists.txt;7;proj_add_gie_test;F:/code/3rdparty/PROJ/PROJ-master/test/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(Deformation "F:/code/3rdparty/PROJ/vs2019/bin/gie.exe" "F:/code/3rdparty/PROJ/PROJ-master/test/gie/deformation.gie")
  set_tests_properties(Deformation PROPERTIES  ENVIRONMENT "PROJ_SKIP_READ_USER_WRITABLE_DIRECTORY=YES;PROJ_LIB=F:/code/3rdparty/PROJ/vs2019/data/for_tests" WORKING_DIRECTORY "F:/code/3rdparty/PROJ/PROJ-master/test" _BACKTRACE_TRIPLES "F:/code/3rdparty/PROJ/PROJ-master/cmake/ProjTest.cmake;31;add_test;F:/code/3rdparty/PROJ/PROJ-master/test/CMakeLists.txt;7;proj_add_gie_test;F:/code/3rdparty/PROJ/PROJ-master/test/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(Deformation "F:/code/3rdparty/PROJ/vs2019/bin/gie.exe" "F:/code/3rdparty/PROJ/PROJ-master/test/gie/deformation.gie")
  set_tests_properties(Deformation PROPERTIES  ENVIRONMENT "PROJ_SKIP_READ_USER_WRITABLE_DIRECTORY=YES;PROJ_LIB=F:/code/3rdparty/PROJ/vs2019/data/for_tests" WORKING_DIRECTORY "F:/code/3rdparty/PROJ/PROJ-master/test" _BACKTRACE_TRIPLES "F:/code/3rdparty/PROJ/PROJ-master/cmake/ProjTest.cmake;31;add_test;F:/code/3rdparty/PROJ/PROJ-master/test/CMakeLists.txt;7;proj_add_gie_test;F:/code/3rdparty/PROJ/PROJ-master/test/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(Deformation "F:/code/3rdparty/PROJ/vs2019/bin/gie.exe" "F:/code/3rdparty/PROJ/PROJ-master/test/gie/deformation.gie")
  set_tests_properties(Deformation PROPERTIES  ENVIRONMENT "PROJ_SKIP_READ_USER_WRITABLE_DIRECTORY=YES;PROJ_LIB=F:/code/3rdparty/PROJ/vs2019/data/for_tests" WORKING_DIRECTORY "F:/code/3rdparty/PROJ/PROJ-master/test" _BACKTRACE_TRIPLES "F:/code/3rdparty/PROJ/PROJ-master/cmake/ProjTest.cmake;31;add_test;F:/code/3rdparty/PROJ/PROJ-master/test/CMakeLists.txt;7;proj_add_gie_test;F:/code/3rdparty/PROJ/PROJ-master/test/CMakeLists.txt;0;")
else()
  add_test(Deformation NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(Ellipsoid "F:/code/3rdparty/PROJ/vs2019/bin/gie_d.exe" "F:/code/3rdparty/PROJ/PROJ-master/test/gie/ellipsoid.gie")
  set_tests_properties(Ellipsoid PROPERTIES  ENVIRONMENT "PROJ_SKIP_READ_USER_WRITABLE_DIRECTORY=YES;PROJ_LIB=F:/code/3rdparty/PROJ/vs2019/data/for_tests" WORKING_DIRECTORY "F:/code/3rdparty/PROJ/PROJ-master/test" _BACKTRACE_TRIPLES "F:/code/3rdparty/PROJ/PROJ-master/cmake/ProjTest.cmake;31;add_test;F:/code/3rdparty/PROJ/PROJ-master/test/CMakeLists.txt;8;proj_add_gie_test;F:/code/3rdparty/PROJ/PROJ-master/test/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(Ellipsoid "F:/code/3rdparty/PROJ/vs2019/bin/gie.exe" "F:/code/3rdparty/PROJ/PROJ-master/test/gie/ellipsoid.gie")
  set_tests_properties(Ellipsoid PROPERTIES  ENVIRONMENT "PROJ_SKIP_READ_USER_WRITABLE_DIRECTORY=YES;PROJ_LIB=F:/code/3rdparty/PROJ/vs2019/data/for_tests" WORKING_DIRECTORY "F:/code/3rdparty/PROJ/PROJ-master/test" _BACKTRACE_TRIPLES "F:/code/3rdparty/PROJ/PROJ-master/cmake/ProjTest.cmake;31;add_test;F:/code/3rdparty/PROJ/PROJ-master/test/CMakeLists.txt;8;proj_add_gie_test;F:/code/3rdparty/PROJ/PROJ-master/test/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(Ellipsoid "F:/code/3rdparty/PROJ/vs2019/bin/gie.exe" "F:/code/3rdparty/PROJ/PROJ-master/test/gie/ellipsoid.gie")
  set_tests_properties(Ellipsoid PROPERTIES  ENVIRONMENT "PROJ_SKIP_READ_USER_WRITABLE_DIRECTORY=YES;PROJ_LIB=F:/code/3rdparty/PROJ/vs2019/data/for_tests" WORKING_DIRECTORY "F:/code/3rdparty/PROJ/PROJ-master/test" _BACKTRACE_TRIPLES "F:/code/3rdparty/PROJ/PROJ-master/cmake/ProjTest.cmake;31;add_test;F:/code/3rdparty/PROJ/PROJ-master/test/CMakeLists.txt;8;proj_add_gie_test;F:/code/3rdparty/PROJ/PROJ-master/test/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(Ellipsoid "F:/code/3rdparty/PROJ/vs2019/bin/gie.exe" "F:/code/3rdparty/PROJ/PROJ-master/test/gie/ellipsoid.gie")
  set_tests_properties(Ellipsoid PROPERTIES  ENVIRONMENT "PROJ_SKIP_READ_USER_WRITABLE_DIRECTORY=YES;PROJ_LIB=F:/code/3rdparty/PROJ/vs2019/data/for_tests" WORKING_DIRECTORY "F:/code/3rdparty/PROJ/PROJ-master/test" _BACKTRACE_TRIPLES "F:/code/3rdparty/PROJ/PROJ-master/cmake/ProjTest.cmake;31;add_test;F:/code/3rdparty/PROJ/PROJ-master/test/CMakeLists.txt;8;proj_add_gie_test;F:/code/3rdparty/PROJ/PROJ-master/test/CMakeLists.txt;0;")
else()
  add_test(Ellipsoid NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(GDA "F:/code/3rdparty/PROJ/vs2019/bin/gie_d.exe" "F:/code/3rdparty/PROJ/PROJ-master/test/gie/GDA.gie")
  set_tests_properties(GDA PROPERTIES  ENVIRONMENT "PROJ_SKIP_READ_USER_WRITABLE_DIRECTORY=YES;PROJ_LIB=F:/code/3rdparty/PROJ/vs2019/data/for_tests" WORKING_DIRECTORY "F:/code/3rdparty/PROJ/PROJ-master/test" _BACKTRACE_TRIPLES "F:/code/3rdparty/PROJ/PROJ-master/cmake/ProjTest.cmake;31;add_test;F:/code/3rdparty/PROJ/PROJ-master/test/CMakeLists.txt;9;proj_add_gie_test;F:/code/3rdparty/PROJ/PROJ-master/test/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(GDA "F:/code/3rdparty/PROJ/vs2019/bin/gie.exe" "F:/code/3rdparty/PROJ/PROJ-master/test/gie/GDA.gie")
  set_tests_properties(GDA PROPERTIES  ENVIRONMENT "PROJ_SKIP_READ_USER_WRITABLE_DIRECTORY=YES;PROJ_LIB=F:/code/3rdparty/PROJ/vs2019/data/for_tests" WORKING_DIRECTORY "F:/code/3rdparty/PROJ/PROJ-master/test" _BACKTRACE_TRIPLES "F:/code/3rdparty/PROJ/PROJ-master/cmake/ProjTest.cmake;31;add_test;F:/code/3rdparty/PROJ/PROJ-master/test/CMakeLists.txt;9;proj_add_gie_test;F:/code/3rdparty/PROJ/PROJ-master/test/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(GDA "F:/code/3rdparty/PROJ/vs2019/bin/gie.exe" "F:/code/3rdparty/PROJ/PROJ-master/test/gie/GDA.gie")
  set_tests_properties(GDA PROPERTIES  ENVIRONMENT "PROJ_SKIP_READ_USER_WRITABLE_DIRECTORY=YES;PROJ_LIB=F:/code/3rdparty/PROJ/vs2019/data/for_tests" WORKING_DIRECTORY "F:/code/3rdparty/PROJ/PROJ-master/test" _BACKTRACE_TRIPLES "F:/code/3rdparty/PROJ/PROJ-master/cmake/ProjTest.cmake;31;add_test;F:/code/3rdparty/PROJ/PROJ-master/test/CMakeLists.txt;9;proj_add_gie_test;F:/code/3rdparty/PROJ/PROJ-master/test/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(GDA "F:/code/3rdparty/PROJ/vs2019/bin/gie.exe" "F:/code/3rdparty/PROJ/PROJ-master/test/gie/GDA.gie")
  set_tests_properties(GDA PROPERTIES  ENVIRONMENT "PROJ_SKIP_READ_USER_WRITABLE_DIRECTORY=YES;PROJ_LIB=F:/code/3rdparty/PROJ/vs2019/data/for_tests" WORKING_DIRECTORY "F:/code/3rdparty/PROJ/PROJ-master/test" _BACKTRACE_TRIPLES "F:/code/3rdparty/PROJ/PROJ-master/cmake/ProjTest.cmake;31;add_test;F:/code/3rdparty/PROJ/PROJ-master/test/CMakeLists.txt;9;proj_add_gie_test;F:/code/3rdparty/PROJ/PROJ-master/test/CMakeLists.txt;0;")
else()
  add_test(GDA NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(4D-API-cs2cs-style "F:/code/3rdparty/PROJ/vs2019/bin/gie_d.exe" "F:/code/3rdparty/PROJ/PROJ-master/test/gie/4D-API_cs2cs-style.gie")
  set_tests_properties(4D-API-cs2cs-style PROPERTIES  ENVIRONMENT "PROJ_SKIP_READ_USER_WRITABLE_DIRECTORY=YES;PROJ_LIB=F:/code/3rdparty/PROJ/vs2019/data/for_tests" WORKING_DIRECTORY "F:/code/3rdparty/PROJ/PROJ-master/test" _BACKTRACE_TRIPLES "F:/code/3rdparty/PROJ/PROJ-master/cmake/ProjTest.cmake;31;add_test;F:/code/3rdparty/PROJ/PROJ-master/test/CMakeLists.txt;10;proj_add_gie_test;F:/code/3rdparty/PROJ/PROJ-master/test/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(4D-API-cs2cs-style "F:/code/3rdparty/PROJ/vs2019/bin/gie.exe" "F:/code/3rdparty/PROJ/PROJ-master/test/gie/4D-API_cs2cs-style.gie")
  set_tests_properties(4D-API-cs2cs-style PROPERTIES  ENVIRONMENT "PROJ_SKIP_READ_USER_WRITABLE_DIRECTORY=YES;PROJ_LIB=F:/code/3rdparty/PROJ/vs2019/data/for_tests" WORKING_DIRECTORY "F:/code/3rdparty/PROJ/PROJ-master/test" _BACKTRACE_TRIPLES "F:/code/3rdparty/PROJ/PROJ-master/cmake/ProjTest.cmake;31;add_test;F:/code/3rdparty/PROJ/PROJ-master/test/CMakeLists.txt;10;proj_add_gie_test;F:/code/3rdparty/PROJ/PROJ-master/test/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(4D-API-cs2cs-style "F:/code/3rdparty/PROJ/vs2019/bin/gie.exe" "F:/code/3rdparty/PROJ/PROJ-master/test/gie/4D-API_cs2cs-style.gie")
  set_tests_properties(4D-API-cs2cs-style PROPERTIES  ENVIRONMENT "PROJ_SKIP_READ_USER_WRITABLE_DIRECTORY=YES;PROJ_LIB=F:/code/3rdparty/PROJ/vs2019/data/for_tests" WORKING_DIRECTORY "F:/code/3rdparty/PROJ/PROJ-master/test" _BACKTRACE_TRIPLES "F:/code/3rdparty/PROJ/PROJ-master/cmake/ProjTest.cmake;31;add_test;F:/code/3rdparty/PROJ/PROJ-master/test/CMakeLists.txt;10;proj_add_gie_test;F:/code/3rdparty/PROJ/PROJ-master/test/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(4D-API-cs2cs-style "F:/code/3rdparty/PROJ/vs2019/bin/gie.exe" "F:/code/3rdparty/PROJ/PROJ-master/test/gie/4D-API_cs2cs-style.gie")
  set_tests_properties(4D-API-cs2cs-style PROPERTIES  ENVIRONMENT "PROJ_SKIP_READ_USER_WRITABLE_DIRECTORY=YES;PROJ_LIB=F:/code/3rdparty/PROJ/vs2019/data/for_tests" WORKING_DIRECTORY "F:/code/3rdparty/PROJ/PROJ-master/test" _BACKTRACE_TRIPLES "F:/code/3rdparty/PROJ/PROJ-master/cmake/ProjTest.cmake;31;add_test;F:/code/3rdparty/PROJ/PROJ-master/test/CMakeLists.txt;10;proj_add_gie_test;F:/code/3rdparty/PROJ/PROJ-master/test/CMakeLists.txt;0;")
else()
  add_test(4D-API-cs2cs-style NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(DHDN_ETRS89 "F:/code/3rdparty/PROJ/vs2019/bin/gie_d.exe" "F:/code/3rdparty/PROJ/PROJ-master/test/gie/DHDN_ETRS89.gie")
  set_tests_properties(DHDN_ETRS89 PROPERTIES  ENVIRONMENT "PROJ_SKIP_READ_USER_WRITABLE_DIRECTORY=YES;PROJ_LIB=F:/code/3rdparty/PROJ/vs2019/data/for_tests" WORKING_DIRECTORY "F:/code/3rdparty/PROJ/PROJ-master/test" _BACKTRACE_TRIPLES "F:/code/3rdparty/PROJ/PROJ-master/cmake/ProjTest.cmake;31;add_test;F:/code/3rdparty/PROJ/PROJ-master/test/CMakeLists.txt;11;proj_add_gie_test;F:/code/3rdparty/PROJ/PROJ-master/test/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(DHDN_ETRS89 "F:/code/3rdparty/PROJ/vs2019/bin/gie.exe" "F:/code/3rdparty/PROJ/PROJ-master/test/gie/DHDN_ETRS89.gie")
  set_tests_properties(DHDN_ETRS89 PROPERTIES  ENVIRONMENT "PROJ_SKIP_READ_USER_WRITABLE_DIRECTORY=YES;PROJ_LIB=F:/code/3rdparty/PROJ/vs2019/data/for_tests" WORKING_DIRECTORY "F:/code/3rdparty/PROJ/PROJ-master/test" _BACKTRACE_TRIPLES "F:/code/3rdparty/PROJ/PROJ-master/cmake/ProjTest.cmake;31;add_test;F:/code/3rdparty/PROJ/PROJ-master/test/CMakeLists.txt;11;proj_add_gie_test;F:/code/3rdparty/PROJ/PROJ-master/test/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(DHDN_ETRS89 "F:/code/3rdparty/PROJ/vs2019/bin/gie.exe" "F:/code/3rdparty/PROJ/PROJ-master/test/gie/DHDN_ETRS89.gie")
  set_tests_properties(DHDN_ETRS89 PROPERTIES  ENVIRONMENT "PROJ_SKIP_READ_USER_WRITABLE_DIRECTORY=YES;PROJ_LIB=F:/code/3rdparty/PROJ/vs2019/data/for_tests" WORKING_DIRECTORY "F:/code/3rdparty/PROJ/PROJ-master/test" _BACKTRACE_TRIPLES "F:/code/3rdparty/PROJ/PROJ-master/cmake/ProjTest.cmake;31;add_test;F:/code/3rdparty/PROJ/PROJ-master/test/CMakeLists.txt;11;proj_add_gie_test;F:/code/3rdparty/PROJ/PROJ-master/test/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(DHDN_ETRS89 "F:/code/3rdparty/PROJ/vs2019/bin/gie.exe" "F:/code/3rdparty/PROJ/PROJ-master/test/gie/DHDN_ETRS89.gie")
  set_tests_properties(DHDN_ETRS89 PROPERTIES  ENVIRONMENT "PROJ_SKIP_READ_USER_WRITABLE_DIRECTORY=YES;PROJ_LIB=F:/code/3rdparty/PROJ/vs2019/data/for_tests" WORKING_DIRECTORY "F:/code/3rdparty/PROJ/PROJ-master/test" _BACKTRACE_TRIPLES "F:/code/3rdparty/PROJ/PROJ-master/cmake/ProjTest.cmake;31;add_test;F:/code/3rdparty/PROJ/PROJ-master/test/CMakeLists.txt;11;proj_add_gie_test;F:/code/3rdparty/PROJ/PROJ-master/test/CMakeLists.txt;0;")
else()
  add_test(DHDN_ETRS89 NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(Unitconvert "F:/code/3rdparty/PROJ/vs2019/bin/gie_d.exe" "F:/code/3rdparty/PROJ/PROJ-master/test/gie/unitconvert.gie")
  set_tests_properties(Unitconvert PROPERTIES  ENVIRONMENT "PROJ_SKIP_READ_USER_WRITABLE_DIRECTORY=YES;PROJ_LIB=F:/code/3rdparty/PROJ/vs2019/data/for_tests" WORKING_DIRECTORY "F:/code/3rdparty/PROJ/PROJ-master/test" _BACKTRACE_TRIPLES "F:/code/3rdparty/PROJ/PROJ-master/cmake/ProjTest.cmake;31;add_test;F:/code/3rdparty/PROJ/PROJ-master/test/CMakeLists.txt;12;proj_add_gie_test;F:/code/3rdparty/PROJ/PROJ-master/test/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(Unitconvert "F:/code/3rdparty/PROJ/vs2019/bin/gie.exe" "F:/code/3rdparty/PROJ/PROJ-master/test/gie/unitconvert.gie")
  set_tests_properties(Unitconvert PROPERTIES  ENVIRONMENT "PROJ_SKIP_READ_USER_WRITABLE_DIRECTORY=YES;PROJ_LIB=F:/code/3rdparty/PROJ/vs2019/data/for_tests" WORKING_DIRECTORY "F:/code/3rdparty/PROJ/PROJ-master/test" _BACKTRACE_TRIPLES "F:/code/3rdparty/PROJ/PROJ-master/cmake/ProjTest.cmake;31;add_test;F:/code/3rdparty/PROJ/PROJ-master/test/CMakeLists.txt;12;proj_add_gie_test;F:/code/3rdparty/PROJ/PROJ-master/test/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(Unitconvert "F:/code/3rdparty/PROJ/vs2019/bin/gie.exe" "F:/code/3rdparty/PROJ/PROJ-master/test/gie/unitconvert.gie")
  set_tests_properties(Unitconvert PROPERTIES  ENVIRONMENT "PROJ_SKIP_READ_USER_WRITABLE_DIRECTORY=YES;PROJ_LIB=F:/code/3rdparty/PROJ/vs2019/data/for_tests" WORKING_DIRECTORY "F:/code/3rdparty/PROJ/PROJ-master/test" _BACKTRACE_TRIPLES "F:/code/3rdparty/PROJ/PROJ-master/cmake/ProjTest.cmake;31;add_test;F:/code/3rdparty/PROJ/PROJ-master/test/CMakeLists.txt;12;proj_add_gie_test;F:/code/3rdparty/PROJ/PROJ-master/test/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(Unitconvert "F:/code/3rdparty/PROJ/vs2019/bin/gie.exe" "F:/code/3rdparty/PROJ/PROJ-master/test/gie/unitconvert.gie")
  set_tests_properties(Unitconvert PROPERTIES  ENVIRONMENT "PROJ_SKIP_READ_USER_WRITABLE_DIRECTORY=YES;PROJ_LIB=F:/code/3rdparty/PROJ/vs2019/data/for_tests" WORKING_DIRECTORY "F:/code/3rdparty/PROJ/PROJ-master/test" _BACKTRACE_TRIPLES "F:/code/3rdparty/PROJ/PROJ-master/cmake/ProjTest.cmake;31;add_test;F:/code/3rdparty/PROJ/PROJ-master/test/CMakeLists.txt;12;proj_add_gie_test;F:/code/3rdparty/PROJ/PROJ-master/test/CMakeLists.txt;0;")
else()
  add_test(Unitconvert NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(geotiff_grids "F:/code/3rdparty/PROJ/vs2019/bin/gie_d.exe" "F:/code/3rdparty/PROJ/PROJ-master/test/gie/geotiff_grids.gie")
  set_tests_properties(geotiff_grids PROPERTIES  ENVIRONMENT "PROJ_SKIP_READ_USER_WRITABLE_DIRECTORY=YES;PROJ_LIB=F:/code/3rdparty/PROJ/vs2019/data/for_tests" WORKING_DIRECTORY "F:/code/3rdparty/PROJ/PROJ-master/test" _BACKTRACE_TRIPLES "F:/code/3rdparty/PROJ/PROJ-master/cmake/ProjTest.cmake;31;add_test;F:/code/3rdparty/PROJ/PROJ-master/test/CMakeLists.txt;13;proj_add_gie_test;F:/code/3rdparty/PROJ/PROJ-master/test/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(geotiff_grids "F:/code/3rdparty/PROJ/vs2019/bin/gie.exe" "F:/code/3rdparty/PROJ/PROJ-master/test/gie/geotiff_grids.gie")
  set_tests_properties(geotiff_grids PROPERTIES  ENVIRONMENT "PROJ_SKIP_READ_USER_WRITABLE_DIRECTORY=YES;PROJ_LIB=F:/code/3rdparty/PROJ/vs2019/data/for_tests" WORKING_DIRECTORY "F:/code/3rdparty/PROJ/PROJ-master/test" _BACKTRACE_TRIPLES "F:/code/3rdparty/PROJ/PROJ-master/cmake/ProjTest.cmake;31;add_test;F:/code/3rdparty/PROJ/PROJ-master/test/CMakeLists.txt;13;proj_add_gie_test;F:/code/3rdparty/PROJ/PROJ-master/test/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(geotiff_grids "F:/code/3rdparty/PROJ/vs2019/bin/gie.exe" "F:/code/3rdparty/PROJ/PROJ-master/test/gie/geotiff_grids.gie")
  set_tests_properties(geotiff_grids PROPERTIES  ENVIRONMENT "PROJ_SKIP_READ_USER_WRITABLE_DIRECTORY=YES;PROJ_LIB=F:/code/3rdparty/PROJ/vs2019/data/for_tests" WORKING_DIRECTORY "F:/code/3rdparty/PROJ/PROJ-master/test" _BACKTRACE_TRIPLES "F:/code/3rdparty/PROJ/PROJ-master/cmake/ProjTest.cmake;31;add_test;F:/code/3rdparty/PROJ/PROJ-master/test/CMakeLists.txt;13;proj_add_gie_test;F:/code/3rdparty/PROJ/PROJ-master/test/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(geotiff_grids "F:/code/3rdparty/PROJ/vs2019/bin/gie.exe" "F:/code/3rdparty/PROJ/PROJ-master/test/gie/geotiff_grids.gie")
  set_tests_properties(geotiff_grids PROPERTIES  ENVIRONMENT "PROJ_SKIP_READ_USER_WRITABLE_DIRECTORY=YES;PROJ_LIB=F:/code/3rdparty/PROJ/vs2019/data/for_tests" WORKING_DIRECTORY "F:/code/3rdparty/PROJ/PROJ-master/test" _BACKTRACE_TRIPLES "F:/code/3rdparty/PROJ/PROJ-master/cmake/ProjTest.cmake;31;add_test;F:/code/3rdparty/PROJ/PROJ-master/test/CMakeLists.txt;13;proj_add_gie_test;F:/code/3rdparty/PROJ/PROJ-master/test/CMakeLists.txt;0;")
else()
  add_test(geotiff_grids NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(adams_hemi "F:/code/3rdparty/PROJ/vs2019/bin/gie_d.exe" "F:/code/3rdparty/PROJ/PROJ-master/test/gie/adams_hemi.gie")
  set_tests_properties(adams_hemi PROPERTIES  ENVIRONMENT "PROJ_SKIP_READ_USER_WRITABLE_DIRECTORY=YES;PROJ_LIB=F:/code/3rdparty/PROJ/vs2019/data/for_tests" WORKING_DIRECTORY "F:/code/3rdparty/PROJ/PROJ-master/test" _BACKTRACE_TRIPLES "F:/code/3rdparty/PROJ/PROJ-master/cmake/ProjTest.cmake;31;add_test;F:/code/3rdparty/PROJ/PROJ-master/test/CMakeLists.txt;14;proj_add_gie_test;F:/code/3rdparty/PROJ/PROJ-master/test/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(adams_hemi "F:/code/3rdparty/PROJ/vs2019/bin/gie.exe" "F:/code/3rdparty/PROJ/PROJ-master/test/gie/adams_hemi.gie")
  set_tests_properties(adams_hemi PROPERTIES  ENVIRONMENT "PROJ_SKIP_READ_USER_WRITABLE_DIRECTORY=YES;PROJ_LIB=F:/code/3rdparty/PROJ/vs2019/data/for_tests" WORKING_DIRECTORY "F:/code/3rdparty/PROJ/PROJ-master/test" _BACKTRACE_TRIPLES "F:/code/3rdparty/PROJ/PROJ-master/cmake/ProjTest.cmake;31;add_test;F:/code/3rdparty/PROJ/PROJ-master/test/CMakeLists.txt;14;proj_add_gie_test;F:/code/3rdparty/PROJ/PROJ-master/test/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(adams_hemi "F:/code/3rdparty/PROJ/vs2019/bin/gie.exe" "F:/code/3rdparty/PROJ/PROJ-master/test/gie/adams_hemi.gie")
  set_tests_properties(adams_hemi PROPERTIES  ENVIRONMENT "PROJ_SKIP_READ_USER_WRITABLE_DIRECTORY=YES;PROJ_LIB=F:/code/3rdparty/PROJ/vs2019/data/for_tests" WORKING_DIRECTORY "F:/code/3rdparty/PROJ/PROJ-master/test" _BACKTRACE_TRIPLES "F:/code/3rdparty/PROJ/PROJ-master/cmake/ProjTest.cmake;31;add_test;F:/code/3rdparty/PROJ/PROJ-master/test/CMakeLists.txt;14;proj_add_gie_test;F:/code/3rdparty/PROJ/PROJ-master/test/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(adams_hemi "F:/code/3rdparty/PROJ/vs2019/bin/gie.exe" "F:/code/3rdparty/PROJ/PROJ-master/test/gie/adams_hemi.gie")
  set_tests_properties(adams_hemi PROPERTIES  ENVIRONMENT "PROJ_SKIP_READ_USER_WRITABLE_DIRECTORY=YES;PROJ_LIB=F:/code/3rdparty/PROJ/vs2019/data/for_tests" WORKING_DIRECTORY "F:/code/3rdparty/PROJ/PROJ-master/test" _BACKTRACE_TRIPLES "F:/code/3rdparty/PROJ/PROJ-master/cmake/ProjTest.cmake;31;add_test;F:/code/3rdparty/PROJ/PROJ-master/test/CMakeLists.txt;14;proj_add_gie_test;F:/code/3rdparty/PROJ/PROJ-master/test/CMakeLists.txt;0;")
else()
  add_test(adams_hemi NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(adams_ws1 "F:/code/3rdparty/PROJ/vs2019/bin/gie_d.exe" "F:/code/3rdparty/PROJ/PROJ-master/test/gie/adams_ws1.gie")
  set_tests_properties(adams_ws1 PROPERTIES  ENVIRONMENT "PROJ_SKIP_READ_USER_WRITABLE_DIRECTORY=YES;PROJ_LIB=F:/code/3rdparty/PROJ/vs2019/data/for_tests" WORKING_DIRECTORY "F:/code/3rdparty/PROJ/PROJ-master/test" _BACKTRACE_TRIPLES "F:/code/3rdparty/PROJ/PROJ-master/cmake/ProjTest.cmake;31;add_test;F:/code/3rdparty/PROJ/PROJ-master/test/CMakeLists.txt;15;proj_add_gie_test;F:/code/3rdparty/PROJ/PROJ-master/test/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(adams_ws1 "F:/code/3rdparty/PROJ/vs2019/bin/gie.exe" "F:/code/3rdparty/PROJ/PROJ-master/test/gie/adams_ws1.gie")
  set_tests_properties(adams_ws1 PROPERTIES  ENVIRONMENT "PROJ_SKIP_READ_USER_WRITABLE_DIRECTORY=YES;PROJ_LIB=F:/code/3rdparty/PROJ/vs2019/data/for_tests" WORKING_DIRECTORY "F:/code/3rdparty/PROJ/PROJ-master/test" _BACKTRACE_TRIPLES "F:/code/3rdparty/PROJ/PROJ-master/cmake/ProjTest.cmake;31;add_test;F:/code/3rdparty/PROJ/PROJ-master/test/CMakeLists.txt;15;proj_add_gie_test;F:/code/3rdparty/PROJ/PROJ-master/test/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(adams_ws1 "F:/code/3rdparty/PROJ/vs2019/bin/gie.exe" "F:/code/3rdparty/PROJ/PROJ-master/test/gie/adams_ws1.gie")
  set_tests_properties(adams_ws1 PROPERTIES  ENVIRONMENT "PROJ_SKIP_READ_USER_WRITABLE_DIRECTORY=YES;PROJ_LIB=F:/code/3rdparty/PROJ/vs2019/data/for_tests" WORKING_DIRECTORY "F:/code/3rdparty/PROJ/PROJ-master/test" _BACKTRACE_TRIPLES "F:/code/3rdparty/PROJ/PROJ-master/cmake/ProjTest.cmake;31;add_test;F:/code/3rdparty/PROJ/PROJ-master/test/CMakeLists.txt;15;proj_add_gie_test;F:/code/3rdparty/PROJ/PROJ-master/test/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(adams_ws1 "F:/code/3rdparty/PROJ/vs2019/bin/gie.exe" "F:/code/3rdparty/PROJ/PROJ-master/test/gie/adams_ws1.gie")
  set_tests_properties(adams_ws1 PROPERTIES  ENVIRONMENT "PROJ_SKIP_READ_USER_WRITABLE_DIRECTORY=YES;PROJ_LIB=F:/code/3rdparty/PROJ/vs2019/data/for_tests" WORKING_DIRECTORY "F:/code/3rdparty/PROJ/PROJ-master/test" _BACKTRACE_TRIPLES "F:/code/3rdparty/PROJ/PROJ-master/cmake/ProjTest.cmake;31;add_test;F:/code/3rdparty/PROJ/PROJ-master/test/CMakeLists.txt;15;proj_add_gie_test;F:/code/3rdparty/PROJ/PROJ-master/test/CMakeLists.txt;0;")
else()
  add_test(adams_ws1 NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(adams_ws2 "F:/code/3rdparty/PROJ/vs2019/bin/gie_d.exe" "F:/code/3rdparty/PROJ/PROJ-master/test/gie/adams_ws2.gie")
  set_tests_properties(adams_ws2 PROPERTIES  ENVIRONMENT "PROJ_SKIP_READ_USER_WRITABLE_DIRECTORY=YES;PROJ_LIB=F:/code/3rdparty/PROJ/vs2019/data/for_tests" WORKING_DIRECTORY "F:/code/3rdparty/PROJ/PROJ-master/test" _BACKTRACE_TRIPLES "F:/code/3rdparty/PROJ/PROJ-master/cmake/ProjTest.cmake;31;add_test;F:/code/3rdparty/PROJ/PROJ-master/test/CMakeLists.txt;16;proj_add_gie_test;F:/code/3rdparty/PROJ/PROJ-master/test/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(adams_ws2 "F:/code/3rdparty/PROJ/vs2019/bin/gie.exe" "F:/code/3rdparty/PROJ/PROJ-master/test/gie/adams_ws2.gie")
  set_tests_properties(adams_ws2 PROPERTIES  ENVIRONMENT "PROJ_SKIP_READ_USER_WRITABLE_DIRECTORY=YES;PROJ_LIB=F:/code/3rdparty/PROJ/vs2019/data/for_tests" WORKING_DIRECTORY "F:/code/3rdparty/PROJ/PROJ-master/test" _BACKTRACE_TRIPLES "F:/code/3rdparty/PROJ/PROJ-master/cmake/ProjTest.cmake;31;add_test;F:/code/3rdparty/PROJ/PROJ-master/test/CMakeLists.txt;16;proj_add_gie_test;F:/code/3rdparty/PROJ/PROJ-master/test/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(adams_ws2 "F:/code/3rdparty/PROJ/vs2019/bin/gie.exe" "F:/code/3rdparty/PROJ/PROJ-master/test/gie/adams_ws2.gie")
  set_tests_properties(adams_ws2 PROPERTIES  ENVIRONMENT "PROJ_SKIP_READ_USER_WRITABLE_DIRECTORY=YES;PROJ_LIB=F:/code/3rdparty/PROJ/vs2019/data/for_tests" WORKING_DIRECTORY "F:/code/3rdparty/PROJ/PROJ-master/test" _BACKTRACE_TRIPLES "F:/code/3rdparty/PROJ/PROJ-master/cmake/ProjTest.cmake;31;add_test;F:/code/3rdparty/PROJ/PROJ-master/test/CMakeLists.txt;16;proj_add_gie_test;F:/code/3rdparty/PROJ/PROJ-master/test/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(adams_ws2 "F:/code/3rdparty/PROJ/vs2019/bin/gie.exe" "F:/code/3rdparty/PROJ/PROJ-master/test/gie/adams_ws2.gie")
  set_tests_properties(adams_ws2 PROPERTIES  ENVIRONMENT "PROJ_SKIP_READ_USER_WRITABLE_DIRECTORY=YES;PROJ_LIB=F:/code/3rdparty/PROJ/vs2019/data/for_tests" WORKING_DIRECTORY "F:/code/3rdparty/PROJ/PROJ-master/test" _BACKTRACE_TRIPLES "F:/code/3rdparty/PROJ/PROJ-master/cmake/ProjTest.cmake;31;add_test;F:/code/3rdparty/PROJ/PROJ-master/test/CMakeLists.txt;16;proj_add_gie_test;F:/code/3rdparty/PROJ/PROJ-master/test/CMakeLists.txt;0;")
else()
  add_test(adams_ws2 NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(guyou "F:/code/3rdparty/PROJ/vs2019/bin/gie_d.exe" "F:/code/3rdparty/PROJ/PROJ-master/test/gie/guyou.gie")
  set_tests_properties(guyou PROPERTIES  ENVIRONMENT "PROJ_SKIP_READ_USER_WRITABLE_DIRECTORY=YES;PROJ_LIB=F:/code/3rdparty/PROJ/vs2019/data/for_tests" WORKING_DIRECTORY "F:/code/3rdparty/PROJ/PROJ-master/test" _BACKTRACE_TRIPLES "F:/code/3rdparty/PROJ/PROJ-master/cmake/ProjTest.cmake;31;add_test;F:/code/3rdparty/PROJ/PROJ-master/test/CMakeLists.txt;17;proj_add_gie_test;F:/code/3rdparty/PROJ/PROJ-master/test/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(guyou "F:/code/3rdparty/PROJ/vs2019/bin/gie.exe" "F:/code/3rdparty/PROJ/PROJ-master/test/gie/guyou.gie")
  set_tests_properties(guyou PROPERTIES  ENVIRONMENT "PROJ_SKIP_READ_USER_WRITABLE_DIRECTORY=YES;PROJ_LIB=F:/code/3rdparty/PROJ/vs2019/data/for_tests" WORKING_DIRECTORY "F:/code/3rdparty/PROJ/PROJ-master/test" _BACKTRACE_TRIPLES "F:/code/3rdparty/PROJ/PROJ-master/cmake/ProjTest.cmake;31;add_test;F:/code/3rdparty/PROJ/PROJ-master/test/CMakeLists.txt;17;proj_add_gie_test;F:/code/3rdparty/PROJ/PROJ-master/test/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(guyou "F:/code/3rdparty/PROJ/vs2019/bin/gie.exe" "F:/code/3rdparty/PROJ/PROJ-master/test/gie/guyou.gie")
  set_tests_properties(guyou PROPERTIES  ENVIRONMENT "PROJ_SKIP_READ_USER_WRITABLE_DIRECTORY=YES;PROJ_LIB=F:/code/3rdparty/PROJ/vs2019/data/for_tests" WORKING_DIRECTORY "F:/code/3rdparty/PROJ/PROJ-master/test" _BACKTRACE_TRIPLES "F:/code/3rdparty/PROJ/PROJ-master/cmake/ProjTest.cmake;31;add_test;F:/code/3rdparty/PROJ/PROJ-master/test/CMakeLists.txt;17;proj_add_gie_test;F:/code/3rdparty/PROJ/PROJ-master/test/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(guyou "F:/code/3rdparty/PROJ/vs2019/bin/gie.exe" "F:/code/3rdparty/PROJ/PROJ-master/test/gie/guyou.gie")
  set_tests_properties(guyou PROPERTIES  ENVIRONMENT "PROJ_SKIP_READ_USER_WRITABLE_DIRECTORY=YES;PROJ_LIB=F:/code/3rdparty/PROJ/vs2019/data/for_tests" WORKING_DIRECTORY "F:/code/3rdparty/PROJ/PROJ-master/test" _BACKTRACE_TRIPLES "F:/code/3rdparty/PROJ/PROJ-master/cmake/ProjTest.cmake;31;add_test;F:/code/3rdparty/PROJ/PROJ-master/test/CMakeLists.txt;17;proj_add_gie_test;F:/code/3rdparty/PROJ/PROJ-master/test/CMakeLists.txt;0;")
else()
  add_test(guyou NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(peirce_q "F:/code/3rdparty/PROJ/vs2019/bin/gie_d.exe" "F:/code/3rdparty/PROJ/PROJ-master/test/gie/peirce_q.gie")
  set_tests_properties(peirce_q PROPERTIES  ENVIRONMENT "PROJ_SKIP_READ_USER_WRITABLE_DIRECTORY=YES;PROJ_LIB=F:/code/3rdparty/PROJ/vs2019/data/for_tests" WORKING_DIRECTORY "F:/code/3rdparty/PROJ/PROJ-master/test" _BACKTRACE_TRIPLES "F:/code/3rdparty/PROJ/PROJ-master/cmake/ProjTest.cmake;31;add_test;F:/code/3rdparty/PROJ/PROJ-master/test/CMakeLists.txt;18;proj_add_gie_test;F:/code/3rdparty/PROJ/PROJ-master/test/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(peirce_q "F:/code/3rdparty/PROJ/vs2019/bin/gie.exe" "F:/code/3rdparty/PROJ/PROJ-master/test/gie/peirce_q.gie")
  set_tests_properties(peirce_q PROPERTIES  ENVIRONMENT "PROJ_SKIP_READ_USER_WRITABLE_DIRECTORY=YES;PROJ_LIB=F:/code/3rdparty/PROJ/vs2019/data/for_tests" WORKING_DIRECTORY "F:/code/3rdparty/PROJ/PROJ-master/test" _BACKTRACE_TRIPLES "F:/code/3rdparty/PROJ/PROJ-master/cmake/ProjTest.cmake;31;add_test;F:/code/3rdparty/PROJ/PROJ-master/test/CMakeLists.txt;18;proj_add_gie_test;F:/code/3rdparty/PROJ/PROJ-master/test/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(peirce_q "F:/code/3rdparty/PROJ/vs2019/bin/gie.exe" "F:/code/3rdparty/PROJ/PROJ-master/test/gie/peirce_q.gie")
  set_tests_properties(peirce_q PROPERTIES  ENVIRONMENT "PROJ_SKIP_READ_USER_WRITABLE_DIRECTORY=YES;PROJ_LIB=F:/code/3rdparty/PROJ/vs2019/data/for_tests" WORKING_DIRECTORY "F:/code/3rdparty/PROJ/PROJ-master/test" _BACKTRACE_TRIPLES "F:/code/3rdparty/PROJ/PROJ-master/cmake/ProjTest.cmake;31;add_test;F:/code/3rdparty/PROJ/PROJ-master/test/CMakeLists.txt;18;proj_add_gie_test;F:/code/3rdparty/PROJ/PROJ-master/test/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(peirce_q "F:/code/3rdparty/PROJ/vs2019/bin/gie.exe" "F:/code/3rdparty/PROJ/PROJ-master/test/gie/peirce_q.gie")
  set_tests_properties(peirce_q PROPERTIES  ENVIRONMENT "PROJ_SKIP_READ_USER_WRITABLE_DIRECTORY=YES;PROJ_LIB=F:/code/3rdparty/PROJ/vs2019/data/for_tests" WORKING_DIRECTORY "F:/code/3rdparty/PROJ/PROJ-master/test" _BACKTRACE_TRIPLES "F:/code/3rdparty/PROJ/PROJ-master/cmake/ProjTest.cmake;31;add_test;F:/code/3rdparty/PROJ/PROJ-master/test/CMakeLists.txt;18;proj_add_gie_test;F:/code/3rdparty/PROJ/PROJ-master/test/CMakeLists.txt;0;")
else()
  add_test(peirce_q NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(defmodel "F:/code/3rdparty/PROJ/vs2019/bin/gie_d.exe" "F:/code/3rdparty/PROJ/PROJ-master/test/gie/defmodel.gie")
  set_tests_properties(defmodel PROPERTIES  ENVIRONMENT "PROJ_SKIP_READ_USER_WRITABLE_DIRECTORY=YES;PROJ_LIB=F:/code/3rdparty/PROJ/vs2019/data/for_tests" WORKING_DIRECTORY "F:/code/3rdparty/PROJ/PROJ-master/test" _BACKTRACE_TRIPLES "F:/code/3rdparty/PROJ/PROJ-master/cmake/ProjTest.cmake;31;add_test;F:/code/3rdparty/PROJ/PROJ-master/test/CMakeLists.txt;19;proj_add_gie_test;F:/code/3rdparty/PROJ/PROJ-master/test/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(defmodel "F:/code/3rdparty/PROJ/vs2019/bin/gie.exe" "F:/code/3rdparty/PROJ/PROJ-master/test/gie/defmodel.gie")
  set_tests_properties(defmodel PROPERTIES  ENVIRONMENT "PROJ_SKIP_READ_USER_WRITABLE_DIRECTORY=YES;PROJ_LIB=F:/code/3rdparty/PROJ/vs2019/data/for_tests" WORKING_DIRECTORY "F:/code/3rdparty/PROJ/PROJ-master/test" _BACKTRACE_TRIPLES "F:/code/3rdparty/PROJ/PROJ-master/cmake/ProjTest.cmake;31;add_test;F:/code/3rdparty/PROJ/PROJ-master/test/CMakeLists.txt;19;proj_add_gie_test;F:/code/3rdparty/PROJ/PROJ-master/test/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(defmodel "F:/code/3rdparty/PROJ/vs2019/bin/gie.exe" "F:/code/3rdparty/PROJ/PROJ-master/test/gie/defmodel.gie")
  set_tests_properties(defmodel PROPERTIES  ENVIRONMENT "PROJ_SKIP_READ_USER_WRITABLE_DIRECTORY=YES;PROJ_LIB=F:/code/3rdparty/PROJ/vs2019/data/for_tests" WORKING_DIRECTORY "F:/code/3rdparty/PROJ/PROJ-master/test" _BACKTRACE_TRIPLES "F:/code/3rdparty/PROJ/PROJ-master/cmake/ProjTest.cmake;31;add_test;F:/code/3rdparty/PROJ/PROJ-master/test/CMakeLists.txt;19;proj_add_gie_test;F:/code/3rdparty/PROJ/PROJ-master/test/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(defmodel "F:/code/3rdparty/PROJ/vs2019/bin/gie.exe" "F:/code/3rdparty/PROJ/PROJ-master/test/gie/defmodel.gie")
  set_tests_properties(defmodel PROPERTIES  ENVIRONMENT "PROJ_SKIP_READ_USER_WRITABLE_DIRECTORY=YES;PROJ_LIB=F:/code/3rdparty/PROJ/vs2019/data/for_tests" WORKING_DIRECTORY "F:/code/3rdparty/PROJ/PROJ-master/test" _BACKTRACE_TRIPLES "F:/code/3rdparty/PROJ/PROJ-master/cmake/ProjTest.cmake;31;add_test;F:/code/3rdparty/PROJ/PROJ-master/test/CMakeLists.txt;19;proj_add_gie_test;F:/code/3rdparty/PROJ/PROJ-master/test/CMakeLists.txt;0;")
else()
  add_test(defmodel NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(GIGS-5101.1-jhs "F:/code/3rdparty/PROJ/vs2019/bin/gie_d.exe" "F:/code/3rdparty/PROJ/PROJ-master/test/gigs/5101.1-jhs.gie")
  set_tests_properties(GIGS-5101.1-jhs PROPERTIES  ENVIRONMENT "PROJ_SKIP_READ_USER_WRITABLE_DIRECTORY=YES;PROJ_LIB=F:/code/3rdparty/PROJ/vs2019/data/for_tests" WORKING_DIRECTORY "F:/code/3rdparty/PROJ/PROJ-master/test" _BACKTRACE_TRIPLES "F:/code/3rdparty/PROJ/PROJ-master/cmake/ProjTest.cmake;31;add_test;F:/code/3rdparty/PROJ/PROJ-master/test/CMakeLists.txt;23;proj_add_gie_test;F:/code/3rdparty/PROJ/PROJ-master/test/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(GIGS-5101.1-jhs "F:/code/3rdparty/PROJ/vs2019/bin/gie.exe" "F:/code/3rdparty/PROJ/PROJ-master/test/gigs/5101.1-jhs.gie")
  set_tests_properties(GIGS-5101.1-jhs PROPERTIES  ENVIRONMENT "PROJ_SKIP_READ_USER_WRITABLE_DIRECTORY=YES;PROJ_LIB=F:/code/3rdparty/PROJ/vs2019/data/for_tests" WORKING_DIRECTORY "F:/code/3rdparty/PROJ/PROJ-master/test" _BACKTRACE_TRIPLES "F:/code/3rdparty/PROJ/PROJ-master/cmake/ProjTest.cmake;31;add_test;F:/code/3rdparty/PROJ/PROJ-master/test/CMakeLists.txt;23;proj_add_gie_test;F:/code/3rdparty/PROJ/PROJ-master/test/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(GIGS-5101.1-jhs "F:/code/3rdparty/PROJ/vs2019/bin/gie.exe" "F:/code/3rdparty/PROJ/PROJ-master/test/gigs/5101.1-jhs.gie")
  set_tests_properties(GIGS-5101.1-jhs PROPERTIES  ENVIRONMENT "PROJ_SKIP_READ_USER_WRITABLE_DIRECTORY=YES;PROJ_LIB=F:/code/3rdparty/PROJ/vs2019/data/for_tests" WORKING_DIRECTORY "F:/code/3rdparty/PROJ/PROJ-master/test" _BACKTRACE_TRIPLES "F:/code/3rdparty/PROJ/PROJ-master/cmake/ProjTest.cmake;31;add_test;F:/code/3rdparty/PROJ/PROJ-master/test/CMakeLists.txt;23;proj_add_gie_test;F:/code/3rdparty/PROJ/PROJ-master/test/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(GIGS-5101.1-jhs "F:/code/3rdparty/PROJ/vs2019/bin/gie.exe" "F:/code/3rdparty/PROJ/PROJ-master/test/gigs/5101.1-jhs.gie")
  set_tests_properties(GIGS-5101.1-jhs PROPERTIES  ENVIRONMENT "PROJ_SKIP_READ_USER_WRITABLE_DIRECTORY=YES;PROJ_LIB=F:/code/3rdparty/PROJ/vs2019/data/for_tests" WORKING_DIRECTORY "F:/code/3rdparty/PROJ/PROJ-master/test" _BACKTRACE_TRIPLES "F:/code/3rdparty/PROJ/PROJ-master/cmake/ProjTest.cmake;31;add_test;F:/code/3rdparty/PROJ/PROJ-master/test/CMakeLists.txt;23;proj_add_gie_test;F:/code/3rdparty/PROJ/PROJ-master/test/CMakeLists.txt;0;")
else()
  add_test(GIGS-5101.1-jhs NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(GIGS-5101.2-jhs "F:/code/3rdparty/PROJ/vs2019/bin/gie_d.exe" "F:/code/3rdparty/PROJ/PROJ-master/test/gigs/5101.2-jhs.gie")
  set_tests_properties(GIGS-5101.2-jhs PROPERTIES  ENVIRONMENT "PROJ_SKIP_READ_USER_WRITABLE_DIRECTORY=YES;PROJ_LIB=F:/code/3rdparty/PROJ/vs2019/data/for_tests" WORKING_DIRECTORY "F:/code/3rdparty/PROJ/PROJ-master/test" _BACKTRACE_TRIPLES "F:/code/3rdparty/PROJ/PROJ-master/cmake/ProjTest.cmake;31;add_test;F:/code/3rdparty/PROJ/PROJ-master/test/CMakeLists.txt;24;proj_add_gie_test;F:/code/3rdparty/PROJ/PROJ-master/test/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(GIGS-5101.2-jhs "F:/code/3rdparty/PROJ/vs2019/bin/gie.exe" "F:/code/3rdparty/PROJ/PROJ-master/test/gigs/5101.2-jhs.gie")
  set_tests_properties(GIGS-5101.2-jhs PROPERTIES  ENVIRONMENT "PROJ_SKIP_READ_USER_WRITABLE_DIRECTORY=YES;PROJ_LIB=F:/code/3rdparty/PROJ/vs2019/data/for_tests" WORKING_DIRECTORY "F:/code/3rdparty/PROJ/PROJ-master/test" _BACKTRACE_TRIPLES "F:/code/3rdparty/PROJ/PROJ-master/cmake/ProjTest.cmake;31;add_test;F:/code/3rdparty/PROJ/PROJ-master/test/CMakeLists.txt;24;proj_add_gie_test;F:/code/3rdparty/PROJ/PROJ-master/test/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(GIGS-5101.2-jhs "F:/code/3rdparty/PROJ/vs2019/bin/gie.exe" "F:/code/3rdparty/PROJ/PROJ-master/test/gigs/5101.2-jhs.gie")
  set_tests_properties(GIGS-5101.2-jhs PROPERTIES  ENVIRONMENT "PROJ_SKIP_READ_USER_WRITABLE_DIRECTORY=YES;PROJ_LIB=F:/code/3rdparty/PROJ/vs2019/data/for_tests" WORKING_DIRECTORY "F:/code/3rdparty/PROJ/PROJ-master/test" _BACKTRACE_TRIPLES "F:/code/3rdparty/PROJ/PROJ-master/cmake/ProjTest.cmake;31;add_test;F:/code/3rdparty/PROJ/PROJ-master/test/CMakeLists.txt;24;proj_add_gie_test;F:/code/3rdparty/PROJ/PROJ-master/test/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(GIGS-5101.2-jhs "F:/code/3rdparty/PROJ/vs2019/bin/gie.exe" "F:/code/3rdparty/PROJ/PROJ-master/test/gigs/5101.2-jhs.gie")
  set_tests_properties(GIGS-5101.2-jhs PROPERTIES  ENVIRONMENT "PROJ_SKIP_READ_USER_WRITABLE_DIRECTORY=YES;PROJ_LIB=F:/code/3rdparty/PROJ/vs2019/data/for_tests" WORKING_DIRECTORY "F:/code/3rdparty/PROJ/PROJ-master/test" _BACKTRACE_TRIPLES "F:/code/3rdparty/PROJ/PROJ-master/cmake/ProjTest.cmake;31;add_test;F:/code/3rdparty/PROJ/PROJ-master/test/CMakeLists.txt;24;proj_add_gie_test;F:/code/3rdparty/PROJ/PROJ-master/test/CMakeLists.txt;0;")
else()
  add_test(GIGS-5101.2-jhs NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(GIGS-5101.3-jhs "F:/code/3rdparty/PROJ/vs2019/bin/gie_d.exe" "F:/code/3rdparty/PROJ/PROJ-master/test/gigs/5101.3-jhs.gie")
  set_tests_properties(GIGS-5101.3-jhs PROPERTIES  ENVIRONMENT "PROJ_SKIP_READ_USER_WRITABLE_DIRECTORY=YES;PROJ_LIB=F:/code/3rdparty/PROJ/vs2019/data/for_tests" WORKING_DIRECTORY "F:/code/3rdparty/PROJ/PROJ-master/test" _BACKTRACE_TRIPLES "F:/code/3rdparty/PROJ/PROJ-master/cmake/ProjTest.cmake;31;add_test;F:/code/3rdparty/PROJ/PROJ-master/test/CMakeLists.txt;25;proj_add_gie_test;F:/code/3rdparty/PROJ/PROJ-master/test/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(GIGS-5101.3-jhs "F:/code/3rdparty/PROJ/vs2019/bin/gie.exe" "F:/code/3rdparty/PROJ/PROJ-master/test/gigs/5101.3-jhs.gie")
  set_tests_properties(GIGS-5101.3-jhs PROPERTIES  ENVIRONMENT "PROJ_SKIP_READ_USER_WRITABLE_DIRECTORY=YES;PROJ_LIB=F:/code/3rdparty/PROJ/vs2019/data/for_tests" WORKING_DIRECTORY "F:/code/3rdparty/PROJ/PROJ-master/test" _BACKTRACE_TRIPLES "F:/code/3rdparty/PROJ/PROJ-master/cmake/ProjTest.cmake;31;add_test;F:/code/3rdparty/PROJ/PROJ-master/test/CMakeLists.txt;25;proj_add_gie_test;F:/code/3rdparty/PROJ/PROJ-master/test/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(GIGS-5101.3-jhs "F:/code/3rdparty/PROJ/vs2019/bin/gie.exe" "F:/code/3rdparty/PROJ/PROJ-master/test/gigs/5101.3-jhs.gie")
  set_tests_properties(GIGS-5101.3-jhs PROPERTIES  ENVIRONMENT "PROJ_SKIP_READ_USER_WRITABLE_DIRECTORY=YES;PROJ_LIB=F:/code/3rdparty/PROJ/vs2019/data/for_tests" WORKING_DIRECTORY "F:/code/3rdparty/PROJ/PROJ-master/test" _BACKTRACE_TRIPLES "F:/code/3rdparty/PROJ/PROJ-master/cmake/ProjTest.cmake;31;add_test;F:/code/3rdparty/PROJ/PROJ-master/test/CMakeLists.txt;25;proj_add_gie_test;F:/code/3rdparty/PROJ/PROJ-master/test/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(GIGS-5101.3-jhs "F:/code/3rdparty/PROJ/vs2019/bin/gie.exe" "F:/code/3rdparty/PROJ/PROJ-master/test/gigs/5101.3-jhs.gie")
  set_tests_properties(GIGS-5101.3-jhs PROPERTIES  ENVIRONMENT "PROJ_SKIP_READ_USER_WRITABLE_DIRECTORY=YES;PROJ_LIB=F:/code/3rdparty/PROJ/vs2019/data/for_tests" WORKING_DIRECTORY "F:/code/3rdparty/PROJ/PROJ-master/test" _BACKTRACE_TRIPLES "F:/code/3rdparty/PROJ/PROJ-master/cmake/ProjTest.cmake;31;add_test;F:/code/3rdparty/PROJ/PROJ-master/test/CMakeLists.txt;25;proj_add_gie_test;F:/code/3rdparty/PROJ/PROJ-master/test/CMakeLists.txt;0;")
else()
  add_test(GIGS-5101.3-jhs NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(GIGS-5101.4-jhs-etmerc "F:/code/3rdparty/PROJ/vs2019/bin/gie_d.exe" "F:/code/3rdparty/PROJ/PROJ-master/test/gigs/5101.4-jhs-etmerc.gie")
  set_tests_properties(GIGS-5101.4-jhs-etmerc PROPERTIES  ENVIRONMENT "PROJ_SKIP_READ_USER_WRITABLE_DIRECTORY=YES;PROJ_LIB=F:/code/3rdparty/PROJ/vs2019/data/for_tests" WORKING_DIRECTORY "F:/code/3rdparty/PROJ/PROJ-master/test" _BACKTRACE_TRIPLES "F:/code/3rdparty/PROJ/PROJ-master/cmake/ProjTest.cmake;31;add_test;F:/code/3rdparty/PROJ/PROJ-master/test/CMakeLists.txt;26;proj_add_gie_test;F:/code/3rdparty/PROJ/PROJ-master/test/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(GIGS-5101.4-jhs-etmerc "F:/code/3rdparty/PROJ/vs2019/bin/gie.exe" "F:/code/3rdparty/PROJ/PROJ-master/test/gigs/5101.4-jhs-etmerc.gie")
  set_tests_properties(GIGS-5101.4-jhs-etmerc PROPERTIES  ENVIRONMENT "PROJ_SKIP_READ_USER_WRITABLE_DIRECTORY=YES;PROJ_LIB=F:/code/3rdparty/PROJ/vs2019/data/for_tests" WORKING_DIRECTORY "F:/code/3rdparty/PROJ/PROJ-master/test" _BACKTRACE_TRIPLES "F:/code/3rdparty/PROJ/PROJ-master/cmake/ProjTest.cmake;31;add_test;F:/code/3rdparty/PROJ/PROJ-master/test/CMakeLists.txt;26;proj_add_gie_test;F:/code/3rdparty/PROJ/PROJ-master/test/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(GIGS-5101.4-jhs-etmerc "F:/code/3rdparty/PROJ/vs2019/bin/gie.exe" "F:/code/3rdparty/PROJ/PROJ-master/test/gigs/5101.4-jhs-etmerc.gie")
  set_tests_properties(GIGS-5101.4-jhs-etmerc PROPERTIES  ENVIRONMENT "PROJ_SKIP_READ_USER_WRITABLE_DIRECTORY=YES;PROJ_LIB=F:/code/3rdparty/PROJ/vs2019/data/for_tests" WORKING_DIRECTORY "F:/code/3rdparty/PROJ/PROJ-master/test" _BACKTRACE_TRIPLES "F:/code/3rdparty/PROJ/PROJ-master/cmake/ProjTest.cmake;31;add_test;F:/code/3rdparty/PROJ/PROJ-master/test/CMakeLists.txt;26;proj_add_gie_test;F:/code/3rdparty/PROJ/PROJ-master/test/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(GIGS-5101.4-jhs-etmerc "F:/code/3rdparty/PROJ/vs2019/bin/gie.exe" "F:/code/3rdparty/PROJ/PROJ-master/test/gigs/5101.4-jhs-etmerc.gie")
  set_tests_properties(GIGS-5101.4-jhs-etmerc PROPERTIES  ENVIRONMENT "PROJ_SKIP_READ_USER_WRITABLE_DIRECTORY=YES;PROJ_LIB=F:/code/3rdparty/PROJ/vs2019/data/for_tests" WORKING_DIRECTORY "F:/code/3rdparty/PROJ/PROJ-master/test" _BACKTRACE_TRIPLES "F:/code/3rdparty/PROJ/PROJ-master/cmake/ProjTest.cmake;31;add_test;F:/code/3rdparty/PROJ/PROJ-master/test/CMakeLists.txt;26;proj_add_gie_test;F:/code/3rdparty/PROJ/PROJ-master/test/CMakeLists.txt;0;")
else()
  add_test(GIGS-5101.4-jhs-etmerc NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(GIGS-5102.1 "F:/code/3rdparty/PROJ/vs2019/bin/gie_d.exe" "F:/code/3rdparty/PROJ/PROJ-master/test/gigs/5102.1.gie")
  set_tests_properties(GIGS-5102.1 PROPERTIES  ENVIRONMENT "PROJ_SKIP_READ_USER_WRITABLE_DIRECTORY=YES;PROJ_LIB=F:/code/3rdparty/PROJ/vs2019/data/for_tests" WORKING_DIRECTORY "F:/code/3rdparty/PROJ/PROJ-master/test" _BACKTRACE_TRIPLES "F:/code/3rdparty/PROJ/PROJ-master/cmake/ProjTest.cmake;31;add_test;F:/code/3rdparty/PROJ/PROJ-master/test/CMakeLists.txt;29;proj_add_gie_test;F:/code/3rdparty/PROJ/PROJ-master/test/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(GIGS-5102.1 "F:/code/3rdparty/PROJ/vs2019/bin/gie.exe" "F:/code/3rdparty/PROJ/PROJ-master/test/gigs/5102.1.gie")
  set_tests_properties(GIGS-5102.1 PROPERTIES  ENVIRONMENT "PROJ_SKIP_READ_USER_WRITABLE_DIRECTORY=YES;PROJ_LIB=F:/code/3rdparty/PROJ/vs2019/data/for_tests" WORKING_DIRECTORY "F:/code/3rdparty/PROJ/PROJ-master/test" _BACKTRACE_TRIPLES "F:/code/3rdparty/PROJ/PROJ-master/cmake/ProjTest.cmake;31;add_test;F:/code/3rdparty/PROJ/PROJ-master/test/CMakeLists.txt;29;proj_add_gie_test;F:/code/3rdparty/PROJ/PROJ-master/test/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(GIGS-5102.1 "F:/code/3rdparty/PROJ/vs2019/bin/gie.exe" "F:/code/3rdparty/PROJ/PROJ-master/test/gigs/5102.1.gie")
  set_tests_properties(GIGS-5102.1 PROPERTIES  ENVIRONMENT "PROJ_SKIP_READ_USER_WRITABLE_DIRECTORY=YES;PROJ_LIB=F:/code/3rdparty/PROJ/vs2019/data/for_tests" WORKING_DIRECTORY "F:/code/3rdparty/PROJ/PROJ-master/test" _BACKTRACE_TRIPLES "F:/code/3rdparty/PROJ/PROJ-master/cmake/ProjTest.cmake;31;add_test;F:/code/3rdparty/PROJ/PROJ-master/test/CMakeLists.txt;29;proj_add_gie_test;F:/code/3rdparty/PROJ/PROJ-master/test/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(GIGS-5102.1 "F:/code/3rdparty/PROJ/vs2019/bin/gie.exe" "F:/code/3rdparty/PROJ/PROJ-master/test/gigs/5102.1.gie")
  set_tests_properties(GIGS-5102.1 PROPERTIES  ENVIRONMENT "PROJ_SKIP_READ_USER_WRITABLE_DIRECTORY=YES;PROJ_LIB=F:/code/3rdparty/PROJ/vs2019/data/for_tests" WORKING_DIRECTORY "F:/code/3rdparty/PROJ/PROJ-master/test" _BACKTRACE_TRIPLES "F:/code/3rdparty/PROJ/PROJ-master/cmake/ProjTest.cmake;31;add_test;F:/code/3rdparty/PROJ/PROJ-master/test/CMakeLists.txt;29;proj_add_gie_test;F:/code/3rdparty/PROJ/PROJ-master/test/CMakeLists.txt;0;")
else()
  add_test(GIGS-5102.1 NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(GIGS-5103.1 "F:/code/3rdparty/PROJ/vs2019/bin/gie_d.exe" "F:/code/3rdparty/PROJ/PROJ-master/test/gigs/5103.1.gie")
  set_tests_properties(GIGS-5103.1 PROPERTIES  ENVIRONMENT "PROJ_SKIP_READ_USER_WRITABLE_DIRECTORY=YES;PROJ_LIB=F:/code/3rdparty/PROJ/vs2019/data/for_tests" WORKING_DIRECTORY "F:/code/3rdparty/PROJ/PROJ-master/test" _BACKTRACE_TRIPLES "F:/code/3rdparty/PROJ/PROJ-master/cmake/ProjTest.cmake;31;add_test;F:/code/3rdparty/PROJ/PROJ-master/test/CMakeLists.txt;31;proj_add_gie_test;F:/code/3rdparty/PROJ/PROJ-master/test/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(GIGS-5103.1 "F:/code/3rdparty/PROJ/vs2019/bin/gie.exe" "F:/code/3rdparty/PROJ/PROJ-master/test/gigs/5103.1.gie")
  set_tests_properties(GIGS-5103.1 PROPERTIES  ENVIRONMENT "PROJ_SKIP_READ_USER_WRITABLE_DIRECTORY=YES;PROJ_LIB=F:/code/3rdparty/PROJ/vs2019/data/for_tests" WORKING_DIRECTORY "F:/code/3rdparty/PROJ/PROJ-master/test" _BACKTRACE_TRIPLES "F:/code/3rdparty/PROJ/PROJ-master/cmake/ProjTest.cmake;31;add_test;F:/code/3rdparty/PROJ/PROJ-master/test/CMakeLists.txt;31;proj_add_gie_test;F:/code/3rdparty/PROJ/PROJ-master/test/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(GIGS-5103.1 "F:/code/3rdparty/PROJ/vs2019/bin/gie.exe" "F:/code/3rdparty/PROJ/PROJ-master/test/gigs/5103.1.gie")
  set_tests_properties(GIGS-5103.1 PROPERTIES  ENVIRONMENT "PROJ_SKIP_READ_USER_WRITABLE_DIRECTORY=YES;PROJ_LIB=F:/code/3rdparty/PROJ/vs2019/data/for_tests" WORKING_DIRECTORY "F:/code/3rdparty/PROJ/PROJ-master/test" _BACKTRACE_TRIPLES "F:/code/3rdparty/PROJ/PROJ-master/cmake/ProjTest.cmake;31;add_test;F:/code/3rdparty/PROJ/PROJ-master/test/CMakeLists.txt;31;proj_add_gie_test;F:/code/3rdparty/PROJ/PROJ-master/test/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(GIGS-5103.1 "F:/code/3rdparty/PROJ/vs2019/bin/gie.exe" "F:/code/3rdparty/PROJ/PROJ-master/test/gigs/5103.1.gie")
  set_tests_properties(GIGS-5103.1 PROPERTIES  ENVIRONMENT "PROJ_SKIP_READ_USER_WRITABLE_DIRECTORY=YES;PROJ_LIB=F:/code/3rdparty/PROJ/vs2019/data/for_tests" WORKING_DIRECTORY "F:/code/3rdparty/PROJ/PROJ-master/test" _BACKTRACE_TRIPLES "F:/code/3rdparty/PROJ/PROJ-master/cmake/ProjTest.cmake;31;add_test;F:/code/3rdparty/PROJ/PROJ-master/test/CMakeLists.txt;31;proj_add_gie_test;F:/code/3rdparty/PROJ/PROJ-master/test/CMakeLists.txt;0;")
else()
  add_test(GIGS-5103.1 NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(GIGS-5103.2 "F:/code/3rdparty/PROJ/vs2019/bin/gie_d.exe" "F:/code/3rdparty/PROJ/PROJ-master/test/gigs/5103.2.gie")
  set_tests_properties(GIGS-5103.2 PROPERTIES  ENVIRONMENT "PROJ_SKIP_READ_USER_WRITABLE_DIRECTORY=YES;PROJ_LIB=F:/code/3rdparty/PROJ/vs2019/data/for_tests" WORKING_DIRECTORY "F:/code/3rdparty/PROJ/PROJ-master/test" _BACKTRACE_TRIPLES "F:/code/3rdparty/PROJ/PROJ-master/cmake/ProjTest.cmake;31;add_test;F:/code/3rdparty/PROJ/PROJ-master/test/CMakeLists.txt;32;proj_add_gie_test;F:/code/3rdparty/PROJ/PROJ-master/test/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(GIGS-5103.2 "F:/code/3rdparty/PROJ/vs2019/bin/gie.exe" "F:/code/3rdparty/PROJ/PROJ-master/test/gigs/5103.2.gie")
  set_tests_properties(GIGS-5103.2 PROPERTIES  ENVIRONMENT "PROJ_SKIP_READ_USER_WRITABLE_DIRECTORY=YES;PROJ_LIB=F:/code/3rdparty/PROJ/vs2019/data/for_tests" WORKING_DIRECTORY "F:/code/3rdparty/PROJ/PROJ-master/test" _BACKTRACE_TRIPLES "F:/code/3rdparty/PROJ/PROJ-master/cmake/ProjTest.cmake;31;add_test;F:/code/3rdparty/PROJ/PROJ-master/test/CMakeLists.txt;32;proj_add_gie_test;F:/code/3rdparty/PROJ/PROJ-master/test/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(GIGS-5103.2 "F:/code/3rdparty/PROJ/vs2019/bin/gie.exe" "F:/code/3rdparty/PROJ/PROJ-master/test/gigs/5103.2.gie")
  set_tests_properties(GIGS-5103.2 PROPERTIES  ENVIRONMENT "PROJ_SKIP_READ_USER_WRITABLE_DIRECTORY=YES;PROJ_LIB=F:/code/3rdparty/PROJ/vs2019/data/for_tests" WORKING_DIRECTORY "F:/code/3rdparty/PROJ/PROJ-master/test" _BACKTRACE_TRIPLES "F:/code/3rdparty/PROJ/PROJ-master/cmake/ProjTest.cmake;31;add_test;F:/code/3rdparty/PROJ/PROJ-master/test/CMakeLists.txt;32;proj_add_gie_test;F:/code/3rdparty/PROJ/PROJ-master/test/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(GIGS-5103.2 "F:/code/3rdparty/PROJ/vs2019/bin/gie.exe" "F:/code/3rdparty/PROJ/PROJ-master/test/gigs/5103.2.gie")
  set_tests_properties(GIGS-5103.2 PROPERTIES  ENVIRONMENT "PROJ_SKIP_READ_USER_WRITABLE_DIRECTORY=YES;PROJ_LIB=F:/code/3rdparty/PROJ/vs2019/data/for_tests" WORKING_DIRECTORY "F:/code/3rdparty/PROJ/PROJ-master/test" _BACKTRACE_TRIPLES "F:/code/3rdparty/PROJ/PROJ-master/cmake/ProjTest.cmake;31;add_test;F:/code/3rdparty/PROJ/PROJ-master/test/CMakeLists.txt;32;proj_add_gie_test;F:/code/3rdparty/PROJ/PROJ-master/test/CMakeLists.txt;0;")
else()
  add_test(GIGS-5103.2 NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(GIGS-5103.3 "F:/code/3rdparty/PROJ/vs2019/bin/gie_d.exe" "F:/code/3rdparty/PROJ/PROJ-master/test/gigs/5103.3.gie")
  set_tests_properties(GIGS-5103.3 PROPERTIES  ENVIRONMENT "PROJ_SKIP_READ_USER_WRITABLE_DIRECTORY=YES;PROJ_LIB=F:/code/3rdparty/PROJ/vs2019/data/for_tests" WORKING_DIRECTORY "F:/code/3rdparty/PROJ/PROJ-master/test" _BACKTRACE_TRIPLES "F:/code/3rdparty/PROJ/PROJ-master/cmake/ProjTest.cmake;31;add_test;F:/code/3rdparty/PROJ/PROJ-master/test/CMakeLists.txt;33;proj_add_gie_test;F:/code/3rdparty/PROJ/PROJ-master/test/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(GIGS-5103.3 "F:/code/3rdparty/PROJ/vs2019/bin/gie.exe" "F:/code/3rdparty/PROJ/PROJ-master/test/gigs/5103.3.gie")
  set_tests_properties(GIGS-5103.3 PROPERTIES  ENVIRONMENT "PROJ_SKIP_READ_USER_WRITABLE_DIRECTORY=YES;PROJ_LIB=F:/code/3rdparty/PROJ/vs2019/data/for_tests" WORKING_DIRECTORY "F:/code/3rdparty/PROJ/PROJ-master/test" _BACKTRACE_TRIPLES "F:/code/3rdparty/PROJ/PROJ-master/cmake/ProjTest.cmake;31;add_test;F:/code/3rdparty/PROJ/PROJ-master/test/CMakeLists.txt;33;proj_add_gie_test;F:/code/3rdparty/PROJ/PROJ-master/test/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(GIGS-5103.3 "F:/code/3rdparty/PROJ/vs2019/bin/gie.exe" "F:/code/3rdparty/PROJ/PROJ-master/test/gigs/5103.3.gie")
  set_tests_properties(GIGS-5103.3 PROPERTIES  ENVIRONMENT "PROJ_SKIP_READ_USER_WRITABLE_DIRECTORY=YES;PROJ_LIB=F:/code/3rdparty/PROJ/vs2019/data/for_tests" WORKING_DIRECTORY "F:/code/3rdparty/PROJ/PROJ-master/test" _BACKTRACE_TRIPLES "F:/code/3rdparty/PROJ/PROJ-master/cmake/ProjTest.cmake;31;add_test;F:/code/3rdparty/PROJ/PROJ-master/test/CMakeLists.txt;33;proj_add_gie_test;F:/code/3rdparty/PROJ/PROJ-master/test/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(GIGS-5103.3 "F:/code/3rdparty/PROJ/vs2019/bin/gie.exe" "F:/code/3rdparty/PROJ/PROJ-master/test/gigs/5103.3.gie")
  set_tests_properties(GIGS-5103.3 PROPERTIES  ENVIRONMENT "PROJ_SKIP_READ_USER_WRITABLE_DIRECTORY=YES;PROJ_LIB=F:/code/3rdparty/PROJ/vs2019/data/for_tests" WORKING_DIRECTORY "F:/code/3rdparty/PROJ/PROJ-master/test" _BACKTRACE_TRIPLES "F:/code/3rdparty/PROJ/PROJ-master/cmake/ProjTest.cmake;31;add_test;F:/code/3rdparty/PROJ/PROJ-master/test/CMakeLists.txt;33;proj_add_gie_test;F:/code/3rdparty/PROJ/PROJ-master/test/CMakeLists.txt;0;")
else()
  add_test(GIGS-5103.3 NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(GIGS-5105.2 "F:/code/3rdparty/PROJ/vs2019/bin/gie_d.exe" "F:/code/3rdparty/PROJ/PROJ-master/test/gigs/5105.2.gie")
  set_tests_properties(GIGS-5105.2 PROPERTIES  ENVIRONMENT "PROJ_SKIP_READ_USER_WRITABLE_DIRECTORY=YES;PROJ_LIB=F:/code/3rdparty/PROJ/vs2019/data/for_tests" WORKING_DIRECTORY "F:/code/3rdparty/PROJ/PROJ-master/test" _BACKTRACE_TRIPLES "F:/code/3rdparty/PROJ/PROJ-master/cmake/ProjTest.cmake;31;add_test;F:/code/3rdparty/PROJ/PROJ-master/test/CMakeLists.txt;36;proj_add_gie_test;F:/code/3rdparty/PROJ/PROJ-master/test/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(GIGS-5105.2 "F:/code/3rdparty/PROJ/vs2019/bin/gie.exe" "F:/code/3rdparty/PROJ/PROJ-master/test/gigs/5105.2.gie")
  set_tests_properties(GIGS-5105.2 PROPERTIES  ENVIRONMENT "PROJ_SKIP_READ_USER_WRITABLE_DIRECTORY=YES;PROJ_LIB=F:/code/3rdparty/PROJ/vs2019/data/for_tests" WORKING_DIRECTORY "F:/code/3rdparty/PROJ/PROJ-master/test" _BACKTRACE_TRIPLES "F:/code/3rdparty/PROJ/PROJ-master/cmake/ProjTest.cmake;31;add_test;F:/code/3rdparty/PROJ/PROJ-master/test/CMakeLists.txt;36;proj_add_gie_test;F:/code/3rdparty/PROJ/PROJ-master/test/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(GIGS-5105.2 "F:/code/3rdparty/PROJ/vs2019/bin/gie.exe" "F:/code/3rdparty/PROJ/PROJ-master/test/gigs/5105.2.gie")
  set_tests_properties(GIGS-5105.2 PROPERTIES  ENVIRONMENT "PROJ_SKIP_READ_USER_WRITABLE_DIRECTORY=YES;PROJ_LIB=F:/code/3rdparty/PROJ/vs2019/data/for_tests" WORKING_DIRECTORY "F:/code/3rdparty/PROJ/PROJ-master/test" _BACKTRACE_TRIPLES "F:/code/3rdparty/PROJ/PROJ-master/cmake/ProjTest.cmake;31;add_test;F:/code/3rdparty/PROJ/PROJ-master/test/CMakeLists.txt;36;proj_add_gie_test;F:/code/3rdparty/PROJ/PROJ-master/test/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(GIGS-5105.2 "F:/code/3rdparty/PROJ/vs2019/bin/gie.exe" "F:/code/3rdparty/PROJ/PROJ-master/test/gigs/5105.2.gie")
  set_tests_properties(GIGS-5105.2 PROPERTIES  ENVIRONMENT "PROJ_SKIP_READ_USER_WRITABLE_DIRECTORY=YES;PROJ_LIB=F:/code/3rdparty/PROJ/vs2019/data/for_tests" WORKING_DIRECTORY "F:/code/3rdparty/PROJ/PROJ-master/test" _BACKTRACE_TRIPLES "F:/code/3rdparty/PROJ/PROJ-master/cmake/ProjTest.cmake;31;add_test;F:/code/3rdparty/PROJ/PROJ-master/test/CMakeLists.txt;36;proj_add_gie_test;F:/code/3rdparty/PROJ/PROJ-master/test/CMakeLists.txt;0;")
else()
  add_test(GIGS-5105.2 NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(GIGS-5106 "F:/code/3rdparty/PROJ/vs2019/bin/gie_d.exe" "F:/code/3rdparty/PROJ/PROJ-master/test/gigs/5106.gie")
  set_tests_properties(GIGS-5106 PROPERTIES  ENVIRONMENT "PROJ_SKIP_READ_USER_WRITABLE_DIRECTORY=YES;PROJ_LIB=F:/code/3rdparty/PROJ/vs2019/data/for_tests" WORKING_DIRECTORY "F:/code/3rdparty/PROJ/PROJ-master/test" _BACKTRACE_TRIPLES "F:/code/3rdparty/PROJ/PROJ-master/cmake/ProjTest.cmake;31;add_test;F:/code/3rdparty/PROJ/PROJ-master/test/CMakeLists.txt;37;proj_add_gie_test;F:/code/3rdparty/PROJ/PROJ-master/test/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(GIGS-5106 "F:/code/3rdparty/PROJ/vs2019/bin/gie.exe" "F:/code/3rdparty/PROJ/PROJ-master/test/gigs/5106.gie")
  set_tests_properties(GIGS-5106 PROPERTIES  ENVIRONMENT "PROJ_SKIP_READ_USER_WRITABLE_DIRECTORY=YES;PROJ_LIB=F:/code/3rdparty/PROJ/vs2019/data/for_tests" WORKING_DIRECTORY "F:/code/3rdparty/PROJ/PROJ-master/test" _BACKTRACE_TRIPLES "F:/code/3rdparty/PROJ/PROJ-master/cmake/ProjTest.cmake;31;add_test;F:/code/3rdparty/PROJ/PROJ-master/test/CMakeLists.txt;37;proj_add_gie_test;F:/code/3rdparty/PROJ/PROJ-master/test/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(GIGS-5106 "F:/code/3rdparty/PROJ/vs2019/bin/gie.exe" "F:/code/3rdparty/PROJ/PROJ-master/test/gigs/5106.gie")
  set_tests_properties(GIGS-5106 PROPERTIES  ENVIRONMENT "PROJ_SKIP_READ_USER_WRITABLE_DIRECTORY=YES;PROJ_LIB=F:/code/3rdparty/PROJ/vs2019/data/for_tests" WORKING_DIRECTORY "F:/code/3rdparty/PROJ/PROJ-master/test" _BACKTRACE_TRIPLES "F:/code/3rdparty/PROJ/PROJ-master/cmake/ProjTest.cmake;31;add_test;F:/code/3rdparty/PROJ/PROJ-master/test/CMakeLists.txt;37;proj_add_gie_test;F:/code/3rdparty/PROJ/PROJ-master/test/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(GIGS-5106 "F:/code/3rdparty/PROJ/vs2019/bin/gie.exe" "F:/code/3rdparty/PROJ/PROJ-master/test/gigs/5106.gie")
  set_tests_properties(GIGS-5106 PROPERTIES  ENVIRONMENT "PROJ_SKIP_READ_USER_WRITABLE_DIRECTORY=YES;PROJ_LIB=F:/code/3rdparty/PROJ/vs2019/data/for_tests" WORKING_DIRECTORY "F:/code/3rdparty/PROJ/PROJ-master/test" _BACKTRACE_TRIPLES "F:/code/3rdparty/PROJ/PROJ-master/cmake/ProjTest.cmake;31;add_test;F:/code/3rdparty/PROJ/PROJ-master/test/CMakeLists.txt;37;proj_add_gie_test;F:/code/3rdparty/PROJ/PROJ-master/test/CMakeLists.txt;0;")
else()
  add_test(GIGS-5106 NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(GIGS-5107 "F:/code/3rdparty/PROJ/vs2019/bin/gie_d.exe" "F:/code/3rdparty/PROJ/PROJ-master/test/gigs/5107.gie")
  set_tests_properties(GIGS-5107 PROPERTIES  ENVIRONMENT "PROJ_SKIP_READ_USER_WRITABLE_DIRECTORY=YES;PROJ_LIB=F:/code/3rdparty/PROJ/vs2019/data/for_tests" WORKING_DIRECTORY "F:/code/3rdparty/PROJ/PROJ-master/test" _BACKTRACE_TRIPLES "F:/code/3rdparty/PROJ/PROJ-master/cmake/ProjTest.cmake;31;add_test;F:/code/3rdparty/PROJ/PROJ-master/test/CMakeLists.txt;38;proj_add_gie_test;F:/code/3rdparty/PROJ/PROJ-master/test/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(GIGS-5107 "F:/code/3rdparty/PROJ/vs2019/bin/gie.exe" "F:/code/3rdparty/PROJ/PROJ-master/test/gigs/5107.gie")
  set_tests_properties(GIGS-5107 PROPERTIES  ENVIRONMENT "PROJ_SKIP_READ_USER_WRITABLE_DIRECTORY=YES;PROJ_LIB=F:/code/3rdparty/PROJ/vs2019/data/for_tests" WORKING_DIRECTORY "F:/code/3rdparty/PROJ/PROJ-master/test" _BACKTRACE_TRIPLES "F:/code/3rdparty/PROJ/PROJ-master/cmake/ProjTest.cmake;31;add_test;F:/code/3rdparty/PROJ/PROJ-master/test/CMakeLists.txt;38;proj_add_gie_test;F:/code/3rdparty/PROJ/PROJ-master/test/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(GIGS-5107 "F:/code/3rdparty/PROJ/vs2019/bin/gie.exe" "F:/code/3rdparty/PROJ/PROJ-master/test/gigs/5107.gie")
  set_tests_properties(GIGS-5107 PROPERTIES  ENVIRONMENT "PROJ_SKIP_READ_USER_WRITABLE_DIRECTORY=YES;PROJ_LIB=F:/code/3rdparty/PROJ/vs2019/data/for_tests" WORKING_DIRECTORY "F:/code/3rdparty/PROJ/PROJ-master/test" _BACKTRACE_TRIPLES "F:/code/3rdparty/PROJ/PROJ-master/cmake/ProjTest.cmake;31;add_test;F:/code/3rdparty/PROJ/PROJ-master/test/CMakeLists.txt;38;proj_add_gie_test;F:/code/3rdparty/PROJ/PROJ-master/test/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(GIGS-5107 "F:/code/3rdparty/PROJ/vs2019/bin/gie.exe" "F:/code/3rdparty/PROJ/PROJ-master/test/gigs/5107.gie")
  set_tests_properties(GIGS-5107 PROPERTIES  ENVIRONMENT "PROJ_SKIP_READ_USER_WRITABLE_DIRECTORY=YES;PROJ_LIB=F:/code/3rdparty/PROJ/vs2019/data/for_tests" WORKING_DIRECTORY "F:/code/3rdparty/PROJ/PROJ-master/test" _BACKTRACE_TRIPLES "F:/code/3rdparty/PROJ/PROJ-master/cmake/ProjTest.cmake;31;add_test;F:/code/3rdparty/PROJ/PROJ-master/test/CMakeLists.txt;38;proj_add_gie_test;F:/code/3rdparty/PROJ/PROJ-master/test/CMakeLists.txt;0;")
else()
  add_test(GIGS-5107 NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(GIGS-5109 "F:/code/3rdparty/PROJ/vs2019/bin/gie_d.exe" "F:/code/3rdparty/PROJ/PROJ-master/test/gigs/5109.gie")
  set_tests_properties(GIGS-5109 PROPERTIES  ENVIRONMENT "PROJ_SKIP_READ_USER_WRITABLE_DIRECTORY=YES;PROJ_LIB=F:/code/3rdparty/PROJ/vs2019/data/for_tests" WORKING_DIRECTORY "F:/code/3rdparty/PROJ/PROJ-master/test" _BACKTRACE_TRIPLES "F:/code/3rdparty/PROJ/PROJ-master/cmake/ProjTest.cmake;31;add_test;F:/code/3rdparty/PROJ/PROJ-master/test/CMakeLists.txt;40;proj_add_gie_test;F:/code/3rdparty/PROJ/PROJ-master/test/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(GIGS-5109 "F:/code/3rdparty/PROJ/vs2019/bin/gie.exe" "F:/code/3rdparty/PROJ/PROJ-master/test/gigs/5109.gie")
  set_tests_properties(GIGS-5109 PROPERTIES  ENVIRONMENT "PROJ_SKIP_READ_USER_WRITABLE_DIRECTORY=YES;PROJ_LIB=F:/code/3rdparty/PROJ/vs2019/data/for_tests" WORKING_DIRECTORY "F:/code/3rdparty/PROJ/PROJ-master/test" _BACKTRACE_TRIPLES "F:/code/3rdparty/PROJ/PROJ-master/cmake/ProjTest.cmake;31;add_test;F:/code/3rdparty/PROJ/PROJ-master/test/CMakeLists.txt;40;proj_add_gie_test;F:/code/3rdparty/PROJ/PROJ-master/test/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(GIGS-5109 "F:/code/3rdparty/PROJ/vs2019/bin/gie.exe" "F:/code/3rdparty/PROJ/PROJ-master/test/gigs/5109.gie")
  set_tests_properties(GIGS-5109 PROPERTIES  ENVIRONMENT "PROJ_SKIP_READ_USER_WRITABLE_DIRECTORY=YES;PROJ_LIB=F:/code/3rdparty/PROJ/vs2019/data/for_tests" WORKING_DIRECTORY "F:/code/3rdparty/PROJ/PROJ-master/test" _BACKTRACE_TRIPLES "F:/code/3rdparty/PROJ/PROJ-master/cmake/ProjTest.cmake;31;add_test;F:/code/3rdparty/PROJ/PROJ-master/test/CMakeLists.txt;40;proj_add_gie_test;F:/code/3rdparty/PROJ/PROJ-master/test/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(GIGS-5109 "F:/code/3rdparty/PROJ/vs2019/bin/gie.exe" "F:/code/3rdparty/PROJ/PROJ-master/test/gigs/5109.gie")
  set_tests_properties(GIGS-5109 PROPERTIES  ENVIRONMENT "PROJ_SKIP_READ_USER_WRITABLE_DIRECTORY=YES;PROJ_LIB=F:/code/3rdparty/PROJ/vs2019/data/for_tests" WORKING_DIRECTORY "F:/code/3rdparty/PROJ/PROJ-master/test" _BACKTRACE_TRIPLES "F:/code/3rdparty/PROJ/PROJ-master/cmake/ProjTest.cmake;31;add_test;F:/code/3rdparty/PROJ/PROJ-master/test/CMakeLists.txt;40;proj_add_gie_test;F:/code/3rdparty/PROJ/PROJ-master/test/CMakeLists.txt;0;")
else()
  add_test(GIGS-5109 NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(GIGS-5111.1 "F:/code/3rdparty/PROJ/vs2019/bin/gie_d.exe" "F:/code/3rdparty/PROJ/PROJ-master/test/gigs/5111.1.gie")
  set_tests_properties(GIGS-5111.1 PROPERTIES  ENVIRONMENT "PROJ_SKIP_READ_USER_WRITABLE_DIRECTORY=YES;PROJ_LIB=F:/code/3rdparty/PROJ/vs2019/data/for_tests" WORKING_DIRECTORY "F:/code/3rdparty/PROJ/PROJ-master/test" _BACKTRACE_TRIPLES "F:/code/3rdparty/PROJ/PROJ-master/cmake/ProjTest.cmake;31;add_test;F:/code/3rdparty/PROJ/PROJ-master/test/CMakeLists.txt;42;proj_add_gie_test;F:/code/3rdparty/PROJ/PROJ-master/test/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(GIGS-5111.1 "F:/code/3rdparty/PROJ/vs2019/bin/gie.exe" "F:/code/3rdparty/PROJ/PROJ-master/test/gigs/5111.1.gie")
  set_tests_properties(GIGS-5111.1 PROPERTIES  ENVIRONMENT "PROJ_SKIP_READ_USER_WRITABLE_DIRECTORY=YES;PROJ_LIB=F:/code/3rdparty/PROJ/vs2019/data/for_tests" WORKING_DIRECTORY "F:/code/3rdparty/PROJ/PROJ-master/test" _BACKTRACE_TRIPLES "F:/code/3rdparty/PROJ/PROJ-master/cmake/ProjTest.cmake;31;add_test;F:/code/3rdparty/PROJ/PROJ-master/test/CMakeLists.txt;42;proj_add_gie_test;F:/code/3rdparty/PROJ/PROJ-master/test/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(GIGS-5111.1 "F:/code/3rdparty/PROJ/vs2019/bin/gie.exe" "F:/code/3rdparty/PROJ/PROJ-master/test/gigs/5111.1.gie")
  set_tests_properties(GIGS-5111.1 PROPERTIES  ENVIRONMENT "PROJ_SKIP_READ_USER_WRITABLE_DIRECTORY=YES;PROJ_LIB=F:/code/3rdparty/PROJ/vs2019/data/for_tests" WORKING_DIRECTORY "F:/code/3rdparty/PROJ/PROJ-master/test" _BACKTRACE_TRIPLES "F:/code/3rdparty/PROJ/PROJ-master/cmake/ProjTest.cmake;31;add_test;F:/code/3rdparty/PROJ/PROJ-master/test/CMakeLists.txt;42;proj_add_gie_test;F:/code/3rdparty/PROJ/PROJ-master/test/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(GIGS-5111.1 "F:/code/3rdparty/PROJ/vs2019/bin/gie.exe" "F:/code/3rdparty/PROJ/PROJ-master/test/gigs/5111.1.gie")
  set_tests_properties(GIGS-5111.1 PROPERTIES  ENVIRONMENT "PROJ_SKIP_READ_USER_WRITABLE_DIRECTORY=YES;PROJ_LIB=F:/code/3rdparty/PROJ/vs2019/data/for_tests" WORKING_DIRECTORY "F:/code/3rdparty/PROJ/PROJ-master/test" _BACKTRACE_TRIPLES "F:/code/3rdparty/PROJ/PROJ-master/cmake/ProjTest.cmake;31;add_test;F:/code/3rdparty/PROJ/PROJ-master/test/CMakeLists.txt;42;proj_add_gie_test;F:/code/3rdparty/PROJ/PROJ-master/test/CMakeLists.txt;0;")
else()
  add_test(GIGS-5111.1 NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(GIGS-5112 "F:/code/3rdparty/PROJ/vs2019/bin/gie_d.exe" "F:/code/3rdparty/PROJ/PROJ-master/test/gigs/5112.gie")
  set_tests_properties(GIGS-5112 PROPERTIES  ENVIRONMENT "PROJ_SKIP_READ_USER_WRITABLE_DIRECTORY=YES;PROJ_LIB=F:/code/3rdparty/PROJ/vs2019/data/for_tests" WORKING_DIRECTORY "F:/code/3rdparty/PROJ/PROJ-master/test" _BACKTRACE_TRIPLES "F:/code/3rdparty/PROJ/PROJ-master/cmake/ProjTest.cmake;31;add_test;F:/code/3rdparty/PROJ/PROJ-master/test/CMakeLists.txt;44;proj_add_gie_test;F:/code/3rdparty/PROJ/PROJ-master/test/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(GIGS-5112 "F:/code/3rdparty/PROJ/vs2019/bin/gie.exe" "F:/code/3rdparty/PROJ/PROJ-master/test/gigs/5112.gie")
  set_tests_properties(GIGS-5112 PROPERTIES  ENVIRONMENT "PROJ_SKIP_READ_USER_WRITABLE_DIRECTORY=YES;PROJ_LIB=F:/code/3rdparty/PROJ/vs2019/data/for_tests" WORKING_DIRECTORY "F:/code/3rdparty/PROJ/PROJ-master/test" _BACKTRACE_TRIPLES "F:/code/3rdparty/PROJ/PROJ-master/cmake/ProjTest.cmake;31;add_test;F:/code/3rdparty/PROJ/PROJ-master/test/CMakeLists.txt;44;proj_add_gie_test;F:/code/3rdparty/PROJ/PROJ-master/test/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(GIGS-5112 "F:/code/3rdparty/PROJ/vs2019/bin/gie.exe" "F:/code/3rdparty/PROJ/PROJ-master/test/gigs/5112.gie")
  set_tests_properties(GIGS-5112 PROPERTIES  ENVIRONMENT "PROJ_SKIP_READ_USER_WRITABLE_DIRECTORY=YES;PROJ_LIB=F:/code/3rdparty/PROJ/vs2019/data/for_tests" WORKING_DIRECTORY "F:/code/3rdparty/PROJ/PROJ-master/test" _BACKTRACE_TRIPLES "F:/code/3rdparty/PROJ/PROJ-master/cmake/ProjTest.cmake;31;add_test;F:/code/3rdparty/PROJ/PROJ-master/test/CMakeLists.txt;44;proj_add_gie_test;F:/code/3rdparty/PROJ/PROJ-master/test/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(GIGS-5112 "F:/code/3rdparty/PROJ/vs2019/bin/gie.exe" "F:/code/3rdparty/PROJ/PROJ-master/test/gigs/5112.gie")
  set_tests_properties(GIGS-5112 PROPERTIES  ENVIRONMENT "PROJ_SKIP_READ_USER_WRITABLE_DIRECTORY=YES;PROJ_LIB=F:/code/3rdparty/PROJ/vs2019/data/for_tests" WORKING_DIRECTORY "F:/code/3rdparty/PROJ/PROJ-master/test" _BACKTRACE_TRIPLES "F:/code/3rdparty/PROJ/PROJ-master/cmake/ProjTest.cmake;31;add_test;F:/code/3rdparty/PROJ/PROJ-master/test/CMakeLists.txt;44;proj_add_gie_test;F:/code/3rdparty/PROJ/PROJ-master/test/CMakeLists.txt;0;")
else()
  add_test(GIGS-5112 NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(GIGS-5113 "F:/code/3rdparty/PROJ/vs2019/bin/gie_d.exe" "F:/code/3rdparty/PROJ/PROJ-master/test/gigs/5113.gie")
  set_tests_properties(GIGS-5113 PROPERTIES  ENVIRONMENT "PROJ_SKIP_READ_USER_WRITABLE_DIRECTORY=YES;PROJ_LIB=F:/code/3rdparty/PROJ/vs2019/data/for_tests" WORKING_DIRECTORY "F:/code/3rdparty/PROJ/PROJ-master/test" _BACKTRACE_TRIPLES "F:/code/3rdparty/PROJ/PROJ-master/cmake/ProjTest.cmake;31;add_test;F:/code/3rdparty/PROJ/PROJ-master/test/CMakeLists.txt;45;proj_add_gie_test;F:/code/3rdparty/PROJ/PROJ-master/test/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(GIGS-5113 "F:/code/3rdparty/PROJ/vs2019/bin/gie.exe" "F:/code/3rdparty/PROJ/PROJ-master/test/gigs/5113.gie")
  set_tests_properties(GIGS-5113 PROPERTIES  ENVIRONMENT "PROJ_SKIP_READ_USER_WRITABLE_DIRECTORY=YES;PROJ_LIB=F:/code/3rdparty/PROJ/vs2019/data/for_tests" WORKING_DIRECTORY "F:/code/3rdparty/PROJ/PROJ-master/test" _BACKTRACE_TRIPLES "F:/code/3rdparty/PROJ/PROJ-master/cmake/ProjTest.cmake;31;add_test;F:/code/3rdparty/PROJ/PROJ-master/test/CMakeLists.txt;45;proj_add_gie_test;F:/code/3rdparty/PROJ/PROJ-master/test/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(GIGS-5113 "F:/code/3rdparty/PROJ/vs2019/bin/gie.exe" "F:/code/3rdparty/PROJ/PROJ-master/test/gigs/5113.gie")
  set_tests_properties(GIGS-5113 PROPERTIES  ENVIRONMENT "PROJ_SKIP_READ_USER_WRITABLE_DIRECTORY=YES;PROJ_LIB=F:/code/3rdparty/PROJ/vs2019/data/for_tests" WORKING_DIRECTORY "F:/code/3rdparty/PROJ/PROJ-master/test" _BACKTRACE_TRIPLES "F:/code/3rdparty/PROJ/PROJ-master/cmake/ProjTest.cmake;31;add_test;F:/code/3rdparty/PROJ/PROJ-master/test/CMakeLists.txt;45;proj_add_gie_test;F:/code/3rdparty/PROJ/PROJ-master/test/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(GIGS-5113 "F:/code/3rdparty/PROJ/vs2019/bin/gie.exe" "F:/code/3rdparty/PROJ/PROJ-master/test/gigs/5113.gie")
  set_tests_properties(GIGS-5113 PROPERTIES  ENVIRONMENT "PROJ_SKIP_READ_USER_WRITABLE_DIRECTORY=YES;PROJ_LIB=F:/code/3rdparty/PROJ/vs2019/data/for_tests" WORKING_DIRECTORY "F:/code/3rdparty/PROJ/PROJ-master/test" _BACKTRACE_TRIPLES "F:/code/3rdparty/PROJ/PROJ-master/cmake/ProjTest.cmake;31;add_test;F:/code/3rdparty/PROJ/PROJ-master/test/CMakeLists.txt;45;proj_add_gie_test;F:/code/3rdparty/PROJ/PROJ-master/test/CMakeLists.txt;0;")
else()
  add_test(GIGS-5113 NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(GIGS-5201 "F:/code/3rdparty/PROJ/vs2019/bin/gie_d.exe" "F:/code/3rdparty/PROJ/PROJ-master/test/gigs/5201.gie")
  set_tests_properties(GIGS-5201 PROPERTIES  ENVIRONMENT "PROJ_SKIP_READ_USER_WRITABLE_DIRECTORY=YES;PROJ_LIB=F:/code/3rdparty/PROJ/vs2019/data/for_tests" WORKING_DIRECTORY "F:/code/3rdparty/PROJ/PROJ-master/test" _BACKTRACE_TRIPLES "F:/code/3rdparty/PROJ/PROJ-master/cmake/ProjTest.cmake;31;add_test;F:/code/3rdparty/PROJ/PROJ-master/test/CMakeLists.txt;46;proj_add_gie_test;F:/code/3rdparty/PROJ/PROJ-master/test/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(GIGS-5201 "F:/code/3rdparty/PROJ/vs2019/bin/gie.exe" "F:/code/3rdparty/PROJ/PROJ-master/test/gigs/5201.gie")
  set_tests_properties(GIGS-5201 PROPERTIES  ENVIRONMENT "PROJ_SKIP_READ_USER_WRITABLE_DIRECTORY=YES;PROJ_LIB=F:/code/3rdparty/PROJ/vs2019/data/for_tests" WORKING_DIRECTORY "F:/code/3rdparty/PROJ/PROJ-master/test" _BACKTRACE_TRIPLES "F:/code/3rdparty/PROJ/PROJ-master/cmake/ProjTest.cmake;31;add_test;F:/code/3rdparty/PROJ/PROJ-master/test/CMakeLists.txt;46;proj_add_gie_test;F:/code/3rdparty/PROJ/PROJ-master/test/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(GIGS-5201 "F:/code/3rdparty/PROJ/vs2019/bin/gie.exe" "F:/code/3rdparty/PROJ/PROJ-master/test/gigs/5201.gie")
  set_tests_properties(GIGS-5201 PROPERTIES  ENVIRONMENT "PROJ_SKIP_READ_USER_WRITABLE_DIRECTORY=YES;PROJ_LIB=F:/code/3rdparty/PROJ/vs2019/data/for_tests" WORKING_DIRECTORY "F:/code/3rdparty/PROJ/PROJ-master/test" _BACKTRACE_TRIPLES "F:/code/3rdparty/PROJ/PROJ-master/cmake/ProjTest.cmake;31;add_test;F:/code/3rdparty/PROJ/PROJ-master/test/CMakeLists.txt;46;proj_add_gie_test;F:/code/3rdparty/PROJ/PROJ-master/test/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(GIGS-5201 "F:/code/3rdparty/PROJ/vs2019/bin/gie.exe" "F:/code/3rdparty/PROJ/PROJ-master/test/gigs/5201.gie")
  set_tests_properties(GIGS-5201 PROPERTIES  ENVIRONMENT "PROJ_SKIP_READ_USER_WRITABLE_DIRECTORY=YES;PROJ_LIB=F:/code/3rdparty/PROJ/vs2019/data/for_tests" WORKING_DIRECTORY "F:/code/3rdparty/PROJ/PROJ-master/test" _BACKTRACE_TRIPLES "F:/code/3rdparty/PROJ/PROJ-master/cmake/ProjTest.cmake;31;add_test;F:/code/3rdparty/PROJ/PROJ-master/test/CMakeLists.txt;46;proj_add_gie_test;F:/code/3rdparty/PROJ/PROJ-master/test/CMakeLists.txt;0;")
else()
  add_test(GIGS-5201 NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(GIGS-5208 "F:/code/3rdparty/PROJ/vs2019/bin/gie_d.exe" "F:/code/3rdparty/PROJ/PROJ-master/test/gigs/5208.gie")
  set_tests_properties(GIGS-5208 PROPERTIES  ENVIRONMENT "PROJ_SKIP_READ_USER_WRITABLE_DIRECTORY=YES;PROJ_LIB=F:/code/3rdparty/PROJ/vs2019/data/for_tests" WORKING_DIRECTORY "F:/code/3rdparty/PROJ/PROJ-master/test" _BACKTRACE_TRIPLES "F:/code/3rdparty/PROJ/PROJ-master/cmake/ProjTest.cmake;31;add_test;F:/code/3rdparty/PROJ/PROJ-master/test/CMakeLists.txt;53;proj_add_gie_test;F:/code/3rdparty/PROJ/PROJ-master/test/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(GIGS-5208 "F:/code/3rdparty/PROJ/vs2019/bin/gie.exe" "F:/code/3rdparty/PROJ/PROJ-master/test/gigs/5208.gie")
  set_tests_properties(GIGS-5208 PROPERTIES  ENVIRONMENT "PROJ_SKIP_READ_USER_WRITABLE_DIRECTORY=YES;PROJ_LIB=F:/code/3rdparty/PROJ/vs2019/data/for_tests" WORKING_DIRECTORY "F:/code/3rdparty/PROJ/PROJ-master/test" _BACKTRACE_TRIPLES "F:/code/3rdparty/PROJ/PROJ-master/cmake/ProjTest.cmake;31;add_test;F:/code/3rdparty/PROJ/PROJ-master/test/CMakeLists.txt;53;proj_add_gie_test;F:/code/3rdparty/PROJ/PROJ-master/test/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(GIGS-5208 "F:/code/3rdparty/PROJ/vs2019/bin/gie.exe" "F:/code/3rdparty/PROJ/PROJ-master/test/gigs/5208.gie")
  set_tests_properties(GIGS-5208 PROPERTIES  ENVIRONMENT "PROJ_SKIP_READ_USER_WRITABLE_DIRECTORY=YES;PROJ_LIB=F:/code/3rdparty/PROJ/vs2019/data/for_tests" WORKING_DIRECTORY "F:/code/3rdparty/PROJ/PROJ-master/test" _BACKTRACE_TRIPLES "F:/code/3rdparty/PROJ/PROJ-master/cmake/ProjTest.cmake;31;add_test;F:/code/3rdparty/PROJ/PROJ-master/test/CMakeLists.txt;53;proj_add_gie_test;F:/code/3rdparty/PROJ/PROJ-master/test/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(GIGS-5208 "F:/code/3rdparty/PROJ/vs2019/bin/gie.exe" "F:/code/3rdparty/PROJ/PROJ-master/test/gigs/5208.gie")
  set_tests_properties(GIGS-5208 PROPERTIES  ENVIRONMENT "PROJ_SKIP_READ_USER_WRITABLE_DIRECTORY=YES;PROJ_LIB=F:/code/3rdparty/PROJ/vs2019/data/for_tests" WORKING_DIRECTORY "F:/code/3rdparty/PROJ/PROJ-master/test" _BACKTRACE_TRIPLES "F:/code/3rdparty/PROJ/PROJ-master/cmake/ProjTest.cmake;31;add_test;F:/code/3rdparty/PROJ/PROJ-master/test/CMakeLists.txt;53;proj_add_gie_test;F:/code/3rdparty/PROJ/PROJ-master/test/CMakeLists.txt;0;")
else()
  add_test(GIGS-5208 NOT_AVAILABLE)
endif()
subdirs("cli")
subdirs("unit")
